from copy import deepcopy


FASHION_PRESET = {
    "name": "شبيك Fashion — التصميم الجاهز 1",
    "description": "قالب أزياء مطابق لبنية الواجهة المرجعية: هيدر عائم، شريط تصنيفات، Hero، عروض، فئات دائرية، تبويبات، أداة فرز وشبكة منتجات.",
    "tokens": {
        "primary": "#E60023",
        "secondary": "#111111",
        "background": "#FFFFFF",
        "surface": "#FFFFFF",
        "muted": "#F7F7F7",
        "text": "#171717",
        "text_muted": "#777777",
        "border": "#EEEEEE",
        "radius": 18,
        "header_mode": "floating",
    },
    "layout": {
        "family": "fashion",
        "header": "fashion-floating",
        "header_height": 64,
        "hero_height": 300,
        "page_padding": 12,
        "section_gap": 10,
        "category_shape": "rounded-square",
        "category_size": 72,
        "category_rows": 3,
        "category_columns": 5,
        "category_gap": 10,
        "category_label_lines": 1,
        "product_card": "rounded",
        "product_columns_mobile": 2,
        "product_columns_desktop": 4,
        "product_gap": 10,
        "product_image_height": 190,
        "show_bottom_nav": True,
        "bottom_nav_style": "pill",
        "bottom_nav_height": 68,
    },
    "sections": [
        {
            "key": "header",
            "type": "header",
            "title": "الهيدر",
            "sort_order": 1,
            "enabled": True,
            "config": {
                "variant": "fashion-floating",
                "show_notifications": True,
                "show_calendar": True,
                "show_camera": True,
                "show_favorites": True,
                "show_search": True,
                "show_category_chips": True,
                "category_chip_limit": 6,
            },
        },
        {
            "key": "hero",
            "type": "hero",
            "title": "البانرات الرئيسية",
            "sort_order": 2,
            "enabled": True,
            "config": {
                "height": 300,
                "autoplay": True,
                "interval_ms": 4500,
                "slides": [],
            },
        },
        {
            "key": "promo_strip",
            "type": "promo_strip",
            "title": "العروض السريعة",
            "sort_order": 3,
            "enabled": True,
            "config": {
                "items": [
                    {"title": "للمستخدمين الجدد فقط", "value": "خصم 30%", "note": "لأول طلب"},
                    {"title": "للمستخدمين الجدد فقط", "value": "خصم 25%", "note": "أكثر من SR379"},
                    {"title": "قسائم حصرية", "value": "عروض جديدة", "note": ""},
                ]
            },
        },
        {
            "key": "category_grid",
            "type": "category_grid",
            "title": "إطلالات وتصنيفات كل",
            "sort_order": 4,
            "enabled": True,
            "config": {
                "source": "all",
                "rows": 3,
                "columns": 5,
                "size": 72,
                "gap": 10,
                "image_fit": "cover",
            },
        },
        {
            "key": "browse_tabs",
            "type": "tabs",
            "title": "التصفح السريع",
            "sort_order": 5,
            "enabled": True,
            "config": {
                "items": [
                    {"id": "best", "title": "الأكثر مبيعًا", "url": "/collection?sort=best"},
                    {"id": "discounts", "title": "خصومات", "url": "/collection?sort=discounts"},
                    {"id": "new", "title": "مقدلات جديدة", "url": "/collection?sort=new"},
                    {"id": "liked", "title": "من أجلك", "url": "/collection?sort=liked"},
                ]
            },
        },
        {
            "key": "catalog_toolbar",
            "type": "catalog_toolbar",
            "title": "المعروضات والتخفيضات",
            "sort_order": 6,
            "enabled": True,
            "config": {
                "show_count": True,
                "show_sort": True,
                "show_filter": True,
                "sort_options": ["أعلى خصم", "الأحدث", "الأكثر مبيعًا"],
                "default_sort": "discounts",
            },
        },
        {
            "key": "products",
            "type": "product_grid",
            "title": "المعروضات والتخفيضات",
            "sort_order": 7,
            "enabled": True,
            "config": {
                "source": "discounts",
                "rows": 6,
                "columns_mobile": 2,
                "columns_desktop": 4,
                "limit": 12,
                "gap": 10,
                "card_style": "rounded",
                "show_see_all": False,
            },
        },
        {
            "key": "bottom_nav",
            "type": "bottom_nav",
            "title": "التنقل السفلي",
            "sort_order": 8,
            "enabled": True,
            "config": {
                "items": [
                    {"label": "حسابي", "icon": "person-outline", "url": "/settings"},
                    {"label": "المفضلة", "icon": "favorite-border", "url": "/favorites"},
                    {"label": "السلة", "icon": "shopping-cart", "url": "/checkout"},
                    {"label": "المنتجات", "icon": "inventory-2", "url": "/collection"},
                    {"label": "الرئيسية", "icon": "home", "url": "/"},
                ]
            },
        },
    ],
}


ELECTRONICS_PRESET = {
    "name": "شبيك Electronics — التصميم الجاهز 2",
    "description": "قالب إلكترونيات مطابق لبنية الواجهة المرجعية: شريط أزرق، بانر عريض، رسالة عروض، شبكة أقسام، ماركات، منتجات وشريط سفلي.",
    "tokens": {
        "primary": "#0D47A1",
        "secondary": "#123B72",
        "background": "#FFFFFF",
        "surface": "#FFFFFF",
        "muted": "#EEF5FF",
        "text": "#151A22",
        "text_muted": "#667085",
        "border": "#E4EAF2",
        "radius": 10,
        "header_mode": "solid",
    },
    "layout": {
        "family": "electronics",
        "header": "electronics-blue",
        "header_height": 112,
        "hero_height": 220,
        "page_padding": 0,
        "section_gap": 0,
        "category_shape": "circle",
        "category_size": 78,
        "category_rows": 3,
        "category_columns": 4,
        "category_gap": 14,
        "category_label_lines": 2,
        "product_card": "square",
        "product_columns_mobile": 2,
        "product_columns_desktop": 5,
        "product_gap": 9,
        "product_image_height": 190,
        "show_bottom_nav": True,
        "bottom_nav_style": "classic",
        "bottom_nav_height": 68,
    },
    "sections": [
        {
            "key": "header",
            "type": "header",
            "title": "الهيدر الأزرق",
            "sort_order": 1,
            "enabled": True,
            "config": {
                "variant": "electronics-blue",
                "show_notifications": True,
                "show_search": True,
                "show_menu": True,
                "show_account": True,
                "show_category_nav": True,
                "category_nav_limit": 6,
            },
        },
        {
            "key": "hero",
            "type": "hero",
            "title": "البانر الرئيسي",
            "sort_order": 2,
            "enabled": True,
            "config": {
                "height": 220,
                "autoplay": True,
                "interval_ms": 5000,
                "slides": [],
            },
        },
        {
            "key": "notice",
            "type": "notice",
            "title": "تنبيه العروض",
            "sort_order": 3,
            "enabled": True,
            "config": {
                "text": "هدية اربح لكم المحافظ التالية (جواني - جيب - فلوسك) وذلك",
                "show_icon": False,
            },
        },
        {
            "key": "category_grid",
            "type": "category_grid",
            "title": "تسوق حسب الأقسام",
            "sort_order": 4,
            "enabled": True,
            "config": {
                "source": "all",
                "rows": 3,
                "columns": 4,
                "size": 78,
                "gap": 14,
                "image_fit": "cover",
            },
        },
        {
            "key": "brand_grid",
            "type": "brand_grid",
            "title": "تسوق حسب الماركة",
            "sort_order": 5,
            "enabled": True,
            "config": {
                "source": "product_brands",
                "rows": 1,
                "columns": 4,
                "size": 88,
                "gap": 16,
                "limit": 8,
            },
        },
        {
            "key": "products",
            "type": "product_grid",
            "title": "أحدث المنتجات",
            "sort_order": 6,
            "enabled": True,
            "config": {
                "source": "latest",
                "rows": 4,
                "columns_mobile": 2,
                "columns_desktop": 5,
                "limit": 10,
                "gap": 9,
                "card_style": "square",
                "show_see_all": True,
            },
        },
        {
            "key": "bottom_nav",
            "type": "bottom_nav",
            "title": "التنقل السفلي",
            "sort_order": 7,
            "enabled": True,
            "config": {
                "items": [
                    {"label": "حسابي", "icon": "person-outline", "url": "/settings"},
                    {"label": "المفضلة", "icon": "favorite-border", "url": "/favorites"},
                    {"label": "السلة", "icon": "shopping-cart", "url": "/checkout"},
                    {"label": "المنتجات", "icon": "inventory-2", "url": "/collection"},
                    {"label": "الرئيسية", "icon": "home", "url": "/"},
                ]
            },
        },
    ],
}


def presets():
    return {"fashion": deepcopy(FASHION_PRESET), "electronics": deepcopy(ELECTRONICS_PRESET)}
