# Generated by Django 5.2.17 on 2026-09-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='UserPreference',
                ),
                migrations.CreateModel(
                    name='UserPreference',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('currency', models.CharField(default='YER', max_length=6)),
                        ('notifications_enabled', models.BooleanField(default=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'تفضيل المستخدم',
                        'verbose_name_plural': 'تفضيلات المستخدمين',
                        'db_table': 'marketplace_userpreference',
                    },
                ),
            ],
        ),
    ]
