LINKS = {
    "yem_query": ("Yemen Mobile - Query", "yem", "GET", "query", {"action": "query"}, {"mobile": "mobile"}, "info", {"action": "status"}),
    "yem_bill_balance": ("Yemen Mobile - Bill Balance", "yem", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "yem_denomination": ("Yemen Mobile - Denomination", "yem", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "yem_offer_query": ("Yemen Mobile - Query Offers", "yem", "GET", "query", {"action": "queryoffer"}, {"mobile": "mobile"}, "info", {"action": "status"}),
    "yem_offer_catalog": ("Yemen Mobile - Offers Catalog", "yem", "GET", "query", {"action": "queryoffer"}, {"mobile": "mobile"}, "info", {"action": "status"}),
    "yem_bill_offer": ("Yemen Mobile - Bill Offer", "yem", "GET", "query", {"action": "billoffer"}, {"mobile": "mobile", "offerid": "external_code", "method": "method"}, "info", {"action": "status"}),
    "yem_offer_bill": ("Yemen Mobile - Combined Offer Bill", "offeryem", "GET", "query", {"action": "billoffer"}, {"mobile": "mobile", "offerkey": "external_code", "method": "method", "solfa": "solfa"}, "info", {"action": "status"}),
    "post_bill_adsl": ("Yemen Post - ADSL", "post", "GET", "query", {"action": "bill", "type": "adsl"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "post_bill_line": ("Yemen Post - Line", "post", "GET", "query", {"action": "bill", "type": "line"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "post_query": ("Yemen Post - Query", "post", "GET", "query", {"action": "query"}, {"mobile": "mobile"}, "info", {"action": "status"}),
    "why_bill": ("Why - Bill", "why", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "why_balance": ("Why - Balance", "why", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num", "rasid": "amount"}, "info", {"action": "status"}),
    "why_package": ("Why - Package", "why", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num", "packageid": "external_code"}, "info", {"action": "status"}),
    "you_balance": ("You - Balance", "mtn", "GET", "query", {"action": "bill", "israsid": "1"}, {"mobile": "mobile", "num": "amount", "type": "type"}, "info", {"action": "status"}),
    "you_denominations": ("You - Denominations", "mtn", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num", "type": "type"}, "info", {"action": "status"}),
    "you_offer": ("You - Offer", "mtnoffer", "GET", "query", {}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "saba_denomination": ("Sabafon - Denomination", "sabaphone", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "saba_offer": ("Sabafon - Offer", "sabaoffer", "GET", "query", {}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "sbay_offer": ("Sabafon South - Offer", "sbayoffer", "GET", "query", {}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "sbay_denominations": ("Sabafon South - Recharge", "sbay", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "saba_units": ("Sabafon - Units", "sabaunits", "GET", "query", {}, {"mobile": "mobile", "num": "amount"}, "info", {"action": "status"}),
    "adenet_bill": ("Aden Net - Bill", "adenet", "GET", "query", {"action": "bill"}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "adenet_query": ("Aden Net - Query", "adenet", "GET", "query", {"action": "query"}, {"mobile": "mobile", "num": "num"}, "info", {"action": "status"}),
    "saba_gomla": ("Sabafon - Wholesale", "sabagomla", "GET", "query", {}, {"mobile": "mobile", "num": "amount"}, "info", {"action": "status"}),
    "mtn_gomla": ("MTN - Wholesale", "mtngomla", "GET", "query", {}, {"mobile": "mobile", "num": "amount"}, "info", {"action": "status"}),
    "mobile_gomla": ("Yemen Mobile - Wholesale", "mobilegomla", "GET", "query", {}, {"mobile": "mobile", "num": "amount"}, "info", {"action": "status"}),
    "yem4g_package": ("Yemen 4G - Package", "yem4g", "GET", "query", {"action": "bill", "type": "1"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "yem4g_balance": ("Yemen 4G - Balance", "yem4g", "GET", "query", {"action": "bill", "type": "2"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "yem4g_change": ("Yemen 4G - Change Package", "yem4g", "GET", "query", {"action": "bill", "type": "3"}, {"mobile": "mobile", "amount": "amount"}, "info", {"action": "status"}),
    "yem4g_query": ("Yemen 4G - Query", "yem4g", "GET", "query", {"action": "query"}, {"mobile": "mobile"}, "info", {"action": "status"}),
    "electric_query": ("Electricity - Query", "electwater", "POST", "form", {"action": "query", "act": "elect"}, {"mobile": "mobile", "customer_id": "customer_id", "placeid": "placeid"}, "info", {"action": "status"}),
    "electric_bill": ("Electricity - Bill", "electwater", "POST", "form", {"action": "bill", "act": "elect"}, {"mobile": "mobile", "customer_id": "customer_id", "placeid": "placeid", "amount": "amount"}, "info", {"action": "status"}),
    "water_query": ("Water - Query", "electwater", "POST", "form", {"action": "query", "act": "water"}, {"mobile": "mobile", "customer_id": "customer_id", "placeid": "placeid"}, "info", {"action": "status"}),
    "water_bill": ("Water - Bill", "electwater", "POST", "form", {"action": "bill", "act": "water"}, {"mobile": "mobile", "customer_id": "customer_id", "placeid": "placeid", "amount": "amount"}, "info", {"action": "status"}),
    "games_cards": ("Games and Cards", "gameswcards", "GET", "query", {}, {"mobile": "mobile", "type": "{{service.code}}", "uniqcode": "uniqcode", "playerid": "playerid", "playername": "playername", "zoneid": "zoneid", "email": "email"}, "info", {"action": "status"}),
}
