import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View, Alert } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { getService, submitService, type Service, type ServiceField } from "@/lib/service-api";

export default function ServiceDetailScreen(){
  const { slug }=useLocalSearchParams<{slug:string}>(); const [service,setService]=useState<Service|null>(null); const [values,setValues]=useState<Record<string,unknown>>({}); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{if(!slug)return;(async()=>{try{setService(await getService(slug))}catch(e){Alert.alert("تعذر تحميل الخدمة","حاول مرة أخرى.")}finally{setLoading(false)}})()},[slug]);
  const canSubmit=useMemo(()=>Boolean(service)&&service!.fields.filter(f=>f.is_required).every(f=>{const v=values[f.key];return v!==undefined&&v!==""&&v!==[]}),[service,values]);
  async function submit(){if(!service||(!canSubmit&&service.fields.some(f=>f.is_required)))return Alert.alert("بيانات ناقصة","أكمل الحقول المطلوبة.");setSubmitting(true);try{const result=await submitService(service.id,values);Alert.alert("تم إرسال الخدمة",`رقم الطلب: ${(result as {reference?:string})?.reference??"تم بنجاح"}`);router.back()}catch(e){Alert.alert("تعذر التنفيذ",e instanceof Error?e.message:"تحقق من الرصيد والبيانات.")}finally{setSubmitting(false)}}
  if(loading)return <ScreenContainer><View style={styles.center}><ActivityIndicator/></View></ScreenContainer>;
  if(!service)return <ScreenContainer><View style={styles.center}><Text>الخدمة غير موجودة</Text></View></ScreenContainer>;
  return <ScreenContainer className="bg-[#F7F7F7]"><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()}><MaterialIcons name="arrow-forward" size={24} color="#111"/></Pressable><Text style={styles.title}>{service.name}</Text><View style={{width:24}}/></View>{service.banner_url||service.image_url?<Image source={{uri:service.banner_url||service.image_url!}} style={styles.banner}/>:<View style={styles.bannerFallback}><Text style={styles.bannerTitle}>{service.name}</Text></View>}<Text style={styles.name}>{service.name}</Text><Text style={styles.desc}>{service.description}</Text>{service.price!=="0.00"&&<View style={styles.priceBox}><Text style={styles.priceLabel}>سعر الخدمة</Text><Text style={styles.price}>{service.price} {service.currency}</Text></View>}<View style={styles.form}>{service.fields.map(field=><Field key={field.id} field={field} value={values[field.key]} onChange={v=>setValues(prev=>({...prev,[field.key]:v}))}/>)}</View><Pressable disabled={submitting} onPress={submit} style={[styles.submit, submitting&&styles.disabled]}><Text style={styles.submitText}>{submitting?"جارٍ الإرسال...":service.price!=="0.00"?"شراء الخدمة وإرسال الطلب":"إرسال الطلب"}</Text></Pressable></ScrollView></ScreenContainer>
}
function Field({field,value,onChange}:{field:ServiceField;value:unknown;onChange:(v:unknown)=>void}){const common={placeholder:field.placeholder||field.label,style:styles.input,textAlign:"right" as const}; if(field.field_type==="textarea")return <View style={styles.field}><Text style={styles.label}>{field.label}{field.is_required?" *":""}</Text><TextInput {...common} multiline numberOfLines={5} value={String(value??"")} onChangeText={onChange}/>{field.help_text?<Text style={styles.help}>{field.help_text}</Text>:null}</View>; if(field.field_type==="checkbox")return <View style={styles.checkRow}><Text style={styles.label}>{field.label}</Text><Switch value={Boolean(value)} onValueChange={onChange}/></View>; if(field.field_type==="select"||field.field_type==="multiselect")return <View style={styles.field}><Text style={styles.label}>{field.label}{field.is_required?" *":""}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.options}>{(field.options||[]).map((opt:any,index)=>{const key=String(opt?.value??opt);const current=Array.isArray(value)?value:[];const selected=field.field_type==="multiselect"?current.includes(key):value===key;return <Pressable key={index} onPress={()=>field.field_type==="multiselect"?onChange(selected?current.filter(x=>x!==key):[...current,key]):onChange(key)} style={[styles.option,selected&&styles.optionActive]}><Text style={[styles.optionText,selected&&styles.optionTextActive]}>{String(opt?.label??opt)}</Text></Pressable>})}</ScrollView></View>; return <View style={styles.field}><Text style={styles.label}>{field.label}{field.is_required?" *":""}</Text><TextInput {...common} keyboardType={field.field_type==="number"?"numeric":field.field_type==="phone"?"phone-pad":"default"} value={String(value??"")} onChangeText={onChange}/>{field.help_text?<Text style={styles.help}>{field.help_text}</Text>:null}</View>}
const styles=StyleSheet.create({content:{paddingBottom:110},header:{height:58,backgroundColor:"#FFF",paddingHorizontal:14,flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:"#EEE"},title:{fontSize:16,fontWeight:"900",color:"#111"},banner:{width:"100%",height:230,backgroundColor:"#EDEDED"},bannerFallback:{height:230,backgroundColor:"#111",alignItems:"center",justifyContent:"center"},bannerTitle:{fontSize:28,fontWeight:"900",color:"#FFF",textAlign:"center"},name:{fontSize:21,fontWeight:"900",color:"#111",textAlign:"right",paddingHorizontal:16,paddingTop:16},desc:{fontSize:12,color:"#666",lineHeight:21,textAlign:"right",paddingHorizontal:16,paddingTop:7},priceBox:{margin:16,padding:14,borderRadius:14,backgroundColor:"#FFF",borderWidth:1,borderColor:"#EEE",flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},priceLabel:{fontSize:11,color:"#777"},price:{fontSize:17,fontWeight:"900",color:"#111"},form:{padding:16,gap:13},field:{gap:6},label:{fontSize:11,fontWeight:"800",color:"#333",textAlign:"right"},input:{minHeight:46,borderWidth:1,borderColor:"#E1E1E1",backgroundColor:"#FFF",borderRadius:12,paddingHorizontal:12,fontSize:13},help:{fontSize:9,color:"#888",textAlign:"right"},checkRow:{padding:12,borderRadius:12,backgroundColor:"#FFF",borderWidth:1,borderColor:"#EEE",flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},options:{gap:8,paddingVertical:2},option:{paddingHorizontal:13,paddingVertical:9,borderRadius:18,borderWidth:1,borderColor:"#DDD",backgroundColor:"#FFF"},optionActive:{backgroundColor:"#111",borderColor:"#111"},optionText:{fontSize:10,color:"#555"},optionTextActive:{color:"#FFF",fontWeight:"800"},submit:{height:50,borderRadius:25,backgroundColor:"#111",marginHorizontal:16,alignItems:"center",justifyContent:"center"},submitText:{color:"#FFF",fontSize:13,fontWeight:"900"},disabled:{opacity:.55},center:{flex:1,alignItems:"center",justifyContent:"center"}});
