import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { getServiceCategories, getServices, type Service, type ServiceCategory } from "@/lib/service-api";

export default function ServicesScreen() {
  const [categories, setCategories] = useState<ServiceCategory[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [active, setActive] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { try { const [c, s] = await Promise.all([getServiceCategories(), getServices()]); setCategories(c.filter((item) => item.parent == null)); setServices(s); } finally { setLoading(false); } })(); }, []);
  const visible = useMemo(() => active == null ? services : services.filter((service) => service.category === active), [active, services]);
  if (loading) return <ScreenContainer className="bg-white"><View style={styles.center}><ActivityIndicator /><Text style={styles.muted}>جارٍ تحميل الخدمات...</Text></View></ScreenContainer>;
  return <ScreenContainer className="bg-[#F7F7F7]"><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={24} color="#111" /></Pressable><Text style={styles.title}>الخدمات</Text><View style={{ width: 24 }} /></View><FlatList data={visible} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.content} numColumns={2} columnWrapperStyle={styles.row} ListHeaderComponent={<FlatList data={categories} horizontal keyExtractor={(item) => String(item.id)} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({ item }) => <Pressable onPress={() => setActive(active === item.id ? null : item.id)} style={[styles.chip, active === item.id && styles.chipActive]}><Text style={[styles.chipText, active === item.id && styles.chipTextActive]}>{item.name}</Text></Pressable>} />} renderItem={({ item }) => <Pressable style={styles.card} onPress={() => router.push(`/services/${item.slug}` as never)}><View style={styles.imageWrap}>{item.image_url ? <Image source={{ uri: item.image_url }} style={styles.image} /> : <MaterialIcons name="miscellaneous-services" size={34} color="#888" />}</View><Text style={styles.name} numberOfLines={2}>{item.name}</Text><Text style={styles.desc} numberOfLines={2}>{item.description || "خدمة متاحة من المنصة"}</Text><Text style={styles.price}>{item.price} {item.currency}</Text></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.name}>لا توجد خدمات حاليًا</Text></View>} /></ScreenContainer>;
}
const styles=StyleSheet.create({header:{height:58,backgroundColor:"#FFF",paddingHorizontal:14,flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:"#EEE"},title:{fontSize:18,fontWeight:"900",color:"#111"},content:{padding:12,paddingBottom:100},chips:{paddingVertical:10,paddingHorizontal:2,gap:8},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:20,backgroundColor:"#FFF",borderWidth:1,borderColor:"#DDD"},chipActive:{backgroundColor:"#111",borderColor:"#111"},chipText:{fontSize:11,color:"#555",fontWeight:"700"},chipTextActive:{color:"#FFF"},row:{gap:10},card:{flex:1,backgroundColor:"#FFF",borderRadius:16,marginBottom:10,padding:10,borderWidth:1,borderColor:"#ECECEC"},imageWrap:{height:125,borderRadius:13,overflow:"hidden",backgroundColor:"#F0F0F0",alignItems:"center",justifyContent:"center"},image:{width:"100%",height:"100%"},name:{fontSize:13,fontWeight:"900",color:"#111",textAlign:"right",marginTop:9},desc:{fontSize:10,color:"#777",lineHeight:16,textAlign:"right",marginTop:4},price:{fontSize:12,fontWeight:"900",color:"#111",textAlign:"right",marginTop:8},center:{flex:1,alignItems:"center",justifyContent:"center",gap:8},muted:{fontSize:11,color:"#888"},empty:{flex:1,alignItems:"center",justifyContent:"center",padding:80}});