# Generated by Django 5.2.17 on 2026-09-03 18:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
        ('vendors', '0002_delete_vendorapplication_delete_vendorprofile_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='CatalogOption'),
                migrations.DeleteModel(name='Category'),
                migrations.DeleteModel(name='PriceGroup'),
                migrations.DeleteModel(name='Product'),
                migrations.DeleteModel(name='ProductImage'),
                migrations.DeleteModel(name='ProductVariant'),
                migrations.CreateModel(name='PriceGroup', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                    ('name', models.CharField(max_length=120)), ('code', models.CharField(max_length=50, unique=True)),
                    ('adjustment_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], max_length=20)),
                    ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                    ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('is_active', models.BooleanField(default=True)),
                ], options={'db_table': 'marketplace_pricegroup'}),
                migrations.CreateModel(name='Category', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                    ('name', models.CharField(max_length=120)), ('slug', models.SlugField(max_length=140, unique=True)),
                    ('image', models.ImageField(blank=True, null=True, upload_to='categories/')), ('is_active', models.BooleanField(default=True)),
                    ('sort_order', models.PositiveIntegerField(default=0)),
                    ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
                ], options={'db_table': 'marketplace_category', 'ordering': ['sort_order', 'name']}),
                migrations.CreateModel(name='City', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                    ('name', models.CharField(max_length=120)), ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                    ('is_active', models.BooleanField(default=True)),
                    ('price_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pricegroup')),
                ], options={'db_table': 'marketplace_city', 'ordering': ['name'], 'indexes': [models.Index(fields=['is_active', 'name'], name='marketplace_is_acti_b54e10_idx')]}),
                migrations.CreateModel(name='Product', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                    ('sku', models.CharField(blank=True, max_length=80, unique=True)), ('name', models.CharField(max_length=220)),
                    ('slug', models.SlugField(blank=True, max_length=240, unique=True)), ('description', models.TextField(blank=True)),
                    ('brand', models.CharField(blank=True, max_length=120)), ('material', models.CharField(blank=True, max_length=180)),
                    ('shipping_note', models.CharField(blank=True, max_length=255)), ('return_policy', models.CharField(blank=True, max_length=255)),
                    ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                    ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                    ('currency', models.CharField(default='YER', max_length=6)), ('stock', models.PositiveIntegerField(default=0)),
                    ('reserved_stock', models.PositiveIntegerField(default=0)), ('colors', models.JSONField(blank=True, default=list)),
                    ('sizes', models.JSONField(blank=True, default=list)), ('hashtags', models.JSONField(blank=True, default=list)),
                    ('details', models.JSONField(blank=True, default=dict)), ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                    ('images', models.JSONField(blank=True, default=list)),
                    ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                    ('reviews_count', models.PositiveIntegerField(default=0)), ('is_published', models.BooleanField(default=False)),
                    ('is_trending', models.BooleanField(default=False)), ('sold_count', models.PositiveIntegerField(default=0)),
                    ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendorprofile')),
                    ('categories', models.ManyToManyField(blank=True, db_table='marketplace_product_categories', related_name='products', to='catalog.category')),
                ], options={'db_table': 'marketplace_product', 'ordering': ['-created_at'], 'indexes': [models.Index(fields=['vendor', 'is_published'], name='marketplace_vendor__e662c7_idx'), models.Index(fields=['sku'], name='marketplace_sku_68aec4_idx'), models.Index(fields=['vendor', 'stock'], name='marketplace_vendor__ede704_idx')]}),
                migrations.CreateModel(name='ProductImage', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                    ('image', models.ImageField(upload_to='products/gallery/')), ('alt_text', models.CharField(blank=True, max_length=180)),
                    ('sort_order', models.PositiveIntegerField(default=0)), ('is_primary', models.BooleanField(default=False)),
                    ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_items', to='catalog.product')),
                ], options={'db_table': 'marketplace_productimage', 'ordering': ['sort_order', 'id']}),
                migrations.CreateModel(name='ProductVariant', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                    ('sku', models.CharField(blank=True, max_length=80, unique=True)), ('color', models.CharField(blank=True, max_length=80)),
                    ('size', models.CharField(blank=True, max_length=80)), ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                    ('stock', models.PositiveIntegerField(default=0)), ('reserved_stock', models.PositiveIntegerField(default=0)), ('is_active', models.BooleanField(default=True)),
                    ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ], options={'db_table': 'marketplace_productvariant', 'indexes': [models.Index(fields=['product', 'stock'], name='marketplace_product_59d90a_idx'), models.Index(fields=['product', 'color', 'size'], name='marketplace_product_a4c812_idx'), models.Index(fields=['product', 'is_active'], name='marketplace_product_2c75f8_idx')]}),
                migrations.CreateModel(name='CatalogOption', fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('group', models.CharField(max_length=60)), ('name', models.CharField(max_length=160)), ('slug', models.SlugField(max_length=180)), ('sort_order', models.PositiveIntegerField(default=0)), ('is_active', models.BooleanField(default=True)),
                    ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_options', to='catalog.category')),
                ], options={'db_table': 'marketplace_catalogoption', 'ordering': ['group', 'sort_order', 'name', 'id'], 'constraints': [models.UniqueConstraint(fields=('group', 'slug', 'category'), name='uniq_catalog_option_group_slug_category')], 'indexes': [models.Index(fields=['group', 'is_active'], name='catopt_grp_active_idx'), models.Index(fields=['category', 'group', 'is_active'], name='catopt_cat_grp_active_idx')]}),
            ],
        )
    ]
