import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { AdminLayout, Colors, Font, Radius, Spacing } from "@/components/admin";
import { apiCall } from "@/lib/_core/api";

type Rate = { id: number; base_currency: string; target_currency: string; rate: string; is_active: boolean };
export default function AdminCurrencyScreen() {
  const [rates,setRates]=useState<Rate[]>([]), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false);
  const [base,setBase]=useState("YER"), [target,setTarget]=useState("SAR"), [rate,setRate]=useState("");
  const load=useCallback(async()=>{try{setLoading(true);const data=await apiCall<{results?:Rate[]}>("/api/currency-rates/");setRates(data.results??[]);}catch(error){Alert.alert("تعذر تحميل أسعار العملات",error instanceof Error?error.message:"حاول مجددًا.");}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  async function save(){const value=Number(rate);if(!Number.isFinite(value)||value<=0)return Alert.alert("سعر غير صالح","أدخل سعر تحويل أكبر من صفر.");try{setSaving(true);const existing=rates.find(x=>x.base_currency===base&&x.target_currency===target);const result=existing?await apiCall<Rate>(`/api/currency-rates/${existing.id}/`,{method:"PATCH",body:JSON.stringify({rate:value,is_active:true})}):await apiCall<Rate>("/api/currency-rates/",{method:"POST",body:JSON.stringify({base_currency:base,target_currency:target,rate:value,is_active:true})});setRates(items=>[...items.filter(x=>x.id!==result.id),result]);setRate("");}catch(error){Alert.alert("تعذر الحفظ",error instanceof Error?error.message:"حاول مجددًا.");}finally{setSaving(false);}}
  async function toggle(item:Rate){try{const result=await apiCall<Rate>(`/api/currency-rates/${item.id}/`,{method:"PATCH",body:JSON.stringify({is_active:!item.is_active})});setRates(items=>items.map(x=>x.id===result.id?result:x));}catch(error){Alert.alert("تعذر التحديث",error instanceof Error?error.message:"حاول مجددًا.");}}
  return <AdminLayout title="أسعار العملات"><ScrollView contentContainerStyle={styles.page}><View style={styles.back}><TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-forward" size={22} color="#111"/></TouchableOpacity></View><View style={styles.card}><Text style={styles.heading}>إضافة أو تحديث سعر تحويل</Text><Text style={styles.help}>يدير المدير أسعار التحويل من مكان واحد، وتعرضها الإعدادات للمستخدم.</Text><Text style={styles.label}>العملة الأساسية</Text><View style={styles.chips}>{["YER","SAR","USD"].map(x=><TouchableOpacity key={x} onPress={()=>setBase(x)} style={[styles.chip,base===x&&styles.chipActive]}><Text style={base===x?styles.chipTextActive:styles.chipText}>{x}</Text></TouchableOpacity>)}</View><Text style={styles.label}>العملة المستهدفة</Text><View style={styles.chips}>{["YER","SAR","USD"].filter(x=>x!==base).map(x=><TouchableOpacity key={x} onPress={()=>setTarget(x)} style={[styles.chip,target===x&&styles.chipActive]}><Text style={target===x?styles.chipTextActive:styles.chipText}>{x}</Text></TouchableOpacity>)}</View><TextInput value={rate} onChangeText={setRate} keyboardType="decimal-pad" placeholder={`سعر ${base} إلى ${target}`} placeholderTextColor="#999" style={styles.input}/><TouchableOpacity disabled={saving} style={styles.save} onPress={save}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.saveText}>حفظ سعر التحويل</Text>}</TouchableOpacity></View>{loading?<ActivityIndicator color={Colors.primary} style={{marginTop:30}}/>:<View style={styles.card}><Text style={styles.heading}>الأسعار الحالية</Text>{rates.map(item=><View key={item.id} style={styles.rateRow}><TouchableOpacity onPress={()=>toggle(item)}><Text style={[styles.toggle,{color:item.is_active?Colors.success:Colors.danger}]}>{item.is_active?"مفعل":"متوقف"}</Text></TouchableOpacity><Text style={styles.value}>{item.rate}</Text><Text style={styles.pair}>{item.base_currency} → {item.target_currency}</Text></View>)}{!rates.length?<Text style={styles.empty}>لا توجد أسعار مضافة بعد.</Text>:null}</View>}</ScrollView></AdminLayout>;
}
const styles=StyleSheet.create({page:{paddingBottom:100},back:{paddingHorizontal:Spacing.lg,paddingTop:Spacing.md},card:{margin:Spacing.lg,marginTop:Spacing.sm,backgroundColor:Colors.surface,borderRadius:Radius.md,padding:Spacing.lg},heading:{color:Colors.text,...Font.sectionTitle,textAlign:"right"},help:{color:Colors.textSecondary,...Font.small,textAlign:"right",marginTop:6,lineHeight:18},label:{color:Colors.text,...Font.small,textAlign:"right",marginTop:15,marginBottom:6},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:7},chip:{paddingHorizontal:13,paddingVertical:9,borderWidth:1,borderColor:Colors.divider,borderRadius:18},chipActive:{backgroundColor:Colors.black,borderColor:Colors.black},chipText:{color:Colors.textSecondary,fontSize:11,fontWeight:"700"},chipTextActive:{color:Colors.textInverse,fontSize:11,fontWeight:"800"},input:{height:46,borderWidth:1,borderColor:Colors.divider,borderRadius:10,marginTop:12,paddingHorizontal:12,textAlign:"right",color:Colors.text},save:{height:48,backgroundColor:Colors.primary,borderRadius:10,alignItems:"center",justifyContent:"center",marginTop:12},saveText:{color:Colors.textInverse,fontWeight:"900"},rateRow:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",paddingVertical:12,borderBottomWidth:1,borderColor:Colors.divider,gap:10},pair:{flex:1,color:Colors.text,fontWeight:"800",textAlign:"right"},value:{color:Colors.text,fontWeight:"900"},toggle:{fontSize:10,fontWeight:"800"},empty:{color:Colors.textSecondary,textAlign:"center",padding:20}});
