import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";

import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { formatYER } from "@/lib/catalog";
import { getAdminOrders, type StoreOrder } from "@/lib/order-api";

export default function AdminOrdersScreen() { const { user, isAuthenticated } = useAuth(); const [orders, setOrders] = useState<StoreOrder[]>([]); const [loading, setLoading] = useState(true); const load = async () => { try { setLoading(true); setOrders(await getAdminOrders()); } finally { setLoading(false); } }; useEffect(() => { if (isAuthenticated && user?.role === "admin") load(); }, [isAuthenticated, user?.role]); if (!isAuthenticated || user?.role !== "admin") return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-white"><View style={styles.center}><MaterialIcons name="lock-outline" size={38} color="#E60023" /><Text style={styles.centerText}>هذه الصفحة للإدارة فقط</Text></View></ScreenContainer>; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><Text style={styles.title}>الطلبات والدردشات</Text><View style={{ width: 23 }} /></View><FlatList style={{ flex: 1 }} data={orders} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshing={loading} onRefresh={load} renderItem={({ item }) => <TouchableOpacity style={styles.card} onPress={() => router.push(`/order/${item.id}` as never)}><MaterialIcons name="chevron-left" size={22} color="#858585" /><View style={styles.copy}><Text style={styles.name}>{item.customer?.name ?? "عميل"} · {item.orderCode}</Text><Text style={styles.meta}>{item.customer?.phone} · {item.items.length} أصناف · {formatYER(item.totalAmount)}</Text><Text style={[styles.status, item.status === "paid_shipping" && styles.done]}>{item.statusLabel}</Text></View><MaterialIcons name="chat-bubble-outline" size={22} color="#171717" /></TouchableOpacity>} ListEmptyComponent={loading ? <ActivityIndicator color="#E60023" style={{ marginTop: 40 }} /> : <View style={styles.center}><MaterialIcons name="forum" size={43} color="#9D9D9D" /><Text style={styles.centerText}>لا توجد طلبات أو دردشات بعد.</Text></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { height: 57, backgroundColor: "#FFFFFF", paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderColor: "#E8E8E8" }, title: { color: "#171717", fontSize: 16, fontWeight: "900" }, list: { padding: 12, paddingBottom: 180 }, card: { backgroundColor: "#FFFFFF", minHeight: 92, padding: 12, marginBottom: 9, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, copy: { flex: 1, alignItems: "flex-end" }, name: { color: "#171717", fontSize: 12, fontWeight: "900", textAlign: "right" }, meta: { color: "#777777", fontSize: 9, marginTop: 4, textAlign: "right" }, status: { color: "#CD7A00", fontSize: 10, marginTop: 4, fontWeight: "700" }, done: { color: "#168451" }, center: { alignItems: "center", justifyContent: "center", paddingTop: 50, gap: 9 }, centerText: { color: "#777777", fontSize: 12, textAlign: "center" },
});
