import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ActivityIndicator, FlatList, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { apiCall } from "@/lib/_core/api";
type Leader = { userId: number; name: string; phone: string; governorate: string; invitedCount: number; referralCode: string };
export default function AdminReferralsScreen() { const [leaders, setLeaders] = useState<Leader[]>([]); const [enabled, setEnabled] = useState(false); const [loading, setLoading] = useState(true); const load = useCallback(async () => { try { setLoading(true); const [setting, data] = await Promise.all([apiCall<{ referral: { isEnabled: boolean } }>("/api/referrals/me").catch(() => ({ referral: { isEnabled: false } })), apiCall<{ referrals: Leader[] }>("/api/admin/referrals")]); setEnabled(setting.referral.isEnabled); setLeaders(data.referrals); } finally { setLoading(false); } }, []); useEffect(() => { load(); }, [load]); const toggle = async (value: boolean) => { setEnabled(value); try { await apiCall("/api/admin/referrals/settings", { method: "PATCH", body: JSON.stringify({ isEnabled: value }) }); } catch { setEnabled(!value); } }; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><Text style={styles.title}>الدعوات والمكافآت</Text><View style={{ width: 23 }} /></View><View style={styles.setting}><Switch value={enabled} onValueChange={toggle} trackColor={{ true: "#E60023" }} /><View><Text style={styles.settingTitle}>تفعيل زر دعوة العملاء</Text><Text style={styles.note}>يبقى مخفيًا في صفحة العميل إلى أن تفعّليه.</Text></View></View>{loading ? <View style={styles.center}><ActivityIndicator color="#E60023" /></View> : <FlatList data={leaders} keyExtractor={(item) => String(item.userId)} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.card}><View><Text style={styles.count}>{item.invitedCount}</Text><Text style={styles.note}>دعوات</Text></View><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.note}>{item.governorate} · {item.phone}</Text></View><MaterialIcons name="group-add" size={24} color="#E60023" /></View>} ListEmptyComponent={<View style={styles.center}><Text style={styles.note}>لا توجد دعوات مسجلة بعد.</Text></View>} />}</ScreenContainer>; }
const styles = StyleSheet.create({ header: { height: 56, backgroundColor: "#FFF", paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 16, fontWeight: "900" }, setting: { backgroundColor: "#FFF", margin: 12, padding: 14, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, settingTitle: { fontWeight: "900", textAlign: "right" }, note: { color: "#777", fontSize: 10, marginTop: 3, textAlign: "right" }, list: { padding: 12, paddingTop: 0 }, card: { backgroundColor: "#FFF", minHeight: 68, marginBottom: 8, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, copy: { flex: 1, alignItems: "flex-end" }, name: { fontSize: 12, fontWeight: "900" }, count: { color: "#E60023", fontWeight: "900", fontSize: 20, textAlign: "center" }, center: { flex: 1, alignItems: "center", justifyContent: "center" } });
