import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { apiCall } from "@/lib/_core/api";
type Thread = { id: number; userId: number; status: string; messages: { id: number; body: string; senderRole: string; createdAt: string }[] };
export default function AdminSupportScreen() { const [threads, setThreads] = useState<Thread[]>([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { try { setLoading(true); setThreads((await apiCall<{ conversations: Thread[] }>("/api/admin/support")).conversations); } finally { setLoading(false); } }, []); useEffect(() => { load(); }, [load]); return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><Text style={styles.title}>محادثات العملاء</Text><View style={{ width: 23 }} /></View>{loading ? <View style={styles.center}><ActivityIndicator color="#E60023" /></View> : <FlatList data={threads} keyExtractor={(item) => String(item.id)} onRefresh={load} refreshing={loading} contentContainerStyle={styles.list} renderItem={({ item }) => { const last = item.messages.at(-1); return <TouchableOpacity style={styles.card} onPress={() => router.push(`/admin/support/${item.id}` as never)}><MaterialIcons name="support-agent" size={24} color="#E60023" /><View style={styles.copy}><Text style={styles.name}>العميل #{item.userId}</Text><Text numberOfLines={1} style={styles.last}>{last?.body || "لم تُرسل رسالة بعد"}</Text></View><MaterialIcons name="chevron-left" size={20} color="#999" /></TouchableOpacity>; }} ListEmptyComponent={<View style={styles.center}><Text style={styles.empty}>لا توجد محادثات دعم بعد.</Text></View>} />}</ScreenContainer>; }
const styles = StyleSheet.create({ header: { height: 56, backgroundColor: "#FFF", paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 16, fontWeight: "900" }, list: { padding: 12 }, card: { backgroundColor: "#FFF", minHeight: 70, marginBottom: 8, flexDirection: "row-reverse", alignItems: "center", padding: 12, gap: 10 }, copy: { flex: 1, alignItems: "flex-end" }, name: { fontWeight: "900", fontSize: 12 }, last: { color: "#777", fontSize: 10, marginTop: 4 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, empty: { color: "#777" } });
