#!/usr/bin/env python3
"""Import the current Django SQLite database into the configured PostgreSQL database.

This is a one-time migration helper. It intentionally refuses to import into a
non-empty application database unless ALLOW_NONEMPTY_TARGET=1 is set.

Required environment:
  DATABASE_URL=postgresql://user:password@host:5432/database

Optional:
  SOURCE_SQLITE_DB=/absolute/path/to/db.sqlite3
  ALLOW_NONEMPTY_TARGET=1
  DB_SSLMODE=require|prefer|disable

Run from backend/:
  python scripts/import_sqlite_to_postgres.py
"""

from __future__ import annotations

import io
import os
import sqlite3
import sys
import tempfile
from pathlib import Path
from urllib.parse import urlparse

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

BASE_DIR = Path(__file__).resolve().parent.parent
SOURCE_SQLITE_DB = Path(
    os.getenv("SOURCE_SQLITE_DB", str(BASE_DIR / "db.sqlite3")
).expanduser().resolve()

# These tables are regenerated by Django migrations or contain ephemeral/admin
# state and are intentionally not copied from the old environment.
EXCLUDED_TABLES = {
    "django_migrations",
    "django_content_type",
    "auth_permission",
    "django_session",
    "django_admin_log",
}
EXCLUDED_LABELS = {
    "contenttypes",
    "auth.permission",
    "sessions",
    "admin.logentry",
}


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def sqlite_tables_and_counts(path: Path) -> dict[str, int]:
    db = sqlite3.connect(path)
    try:
        rows = db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()
        result: dict[str, int] = {}
        for (table_name,) in rows:
            result[table_name] = int(
                db.execute(f'SELECT COUNT(*) FROM "{table_name}"').fetchone()[0]
            )
        return result
    finally:
        db.close()


def postgres_table_counts(connection) -> dict[str, int]:
    tables = connection.introspection.table_names()
    counts: dict[str, int] = {}
    with connection.cursor() as cursor:
        for table_name in tables:
            quoted = connection.ops.quote_name(table_name)
            cursor.execute(f"SELECT COUNT(*) FROM {quoted}")
            counts[table_name] = int(cursor.fetchone()[0])
    return counts


def main() -> int:
    if not SOURCE_SQLITE_DB.is_file():
        fail(f"SQLite source database not found: {SOURCE_SQLITE_DB}")

    database_url = os.getenv("DATABASE_URL", "").strip()
    if not database_url:
        fail("DATABASE_URL is required for the PostgreSQL target.")
    if urlparse(database_url).scheme not in {"postgres", "postgresql"}:
        fail("DATABASE_URL must use postgres:// or postgresql://")

    source_counts = sqlite_tables_and_counts(SOURCE_SQLITE_DB)
    source_data_tables = {
        table: count
        for table, count in source_counts.items()
        if table not in EXCLUDED_TABLES
    }
    source_total = sum(source_counts.values())
    source_data_total = sum(source_data_tables.values())

    print(f"SQLite source: {SOURCE_SQLITE_DB}")
    print(f"SQLite tables: {len(source_counts)}")
    print(f"SQLite total rows: {source_total}")
    print(f"Rows eligible for import: {source_data_total}")

    import django

    django.setup()

    from django.apps import apps
    from django.core.management import call_command
    from django.core.management.color import no_style
    from django.db import connections, transaction

    # Add the SQLite source as a second Django DB alias while keeping the
    # configured PostgreSQL connection as the default target.
    connections.databases["source"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(SOURCE_SQLITE_DB),
    }
    source_connection = connections["source"]
    target_connection = connections["default"]

    source_connection.ensure_connection()
    target_connection.ensure_connection()

    print("Applying Django migrations to the PostgreSQL target...")
    call_command("migrate", database="default", interactive=False, verbosity=1)

    target_counts_before = postgres_table_counts(target_connection)
    nonempty_target = {
        table: count
        for table, count in target_counts_before.items()
        if table in source_data_tables and count > 0
    }
    if nonempty_target and os.getenv("ALLOW_NONEMPTY_TARGET", "0") != "1":
        preview = ", ".join(
            f"{table}={count}" for table, count in sorted(nonempty_target.items())[:20]
        )
        fail(
            "PostgreSQL target already contains application data; refusing to mix "
            f"datasets. Existing rows: {preview}. Use a fresh database or explicitly "
            "set ALLOW_NONEMPTY_TARGET=1 after taking a backup."
        )

    print("Exporting Django data from SQLite...")
    fixture = tempfile.NamedTemporaryFile(
        mode="w+", suffix=".json", prefix="marketplace-migration-", delete=False
    )
    fixture_path = Path(fixture.name)
    fixture.close()

    try:
        command_kwargs = {
            "database": "source",
            "use_natural_foreign_keys": True,
            "use_natural_primary_keys": False,
            "indent": 2,
            "stdout": open(fixture_path, "w", encoding="utf-8"),
        }
        for label in EXCLUDED_LABELS:
            command_kwargs.setdefault("exclude", []).append(label)
        try:
            call_command("dumpdata", **command_kwargs)
        finally:
            command_kwargs["stdout"].close()

        print("Importing fixture into PostgreSQL...")
        with transaction.atomic(using="default"):
            call_command(
                "loaddata",
                str(fixture_path),
                database="default",
                verbosity=1,
            )

            print("Resetting PostgreSQL sequences...")
            models = [
                model
                for model in apps.get_models()
                if model._meta.managed and not model._meta.proxy
            ]
            reset_sql = target_connection.ops.sequence_reset_sql(no_style(), models)
            with target_connection.cursor() as cursor:
                for statement in reset_sql:
                    cursor.execute(statement)

        print("Verifying row counts table-by-table...")
        target_counts_after = postgres_table_counts(target_connection)
        mismatches: list[tuple[str, int, int | None]] = []
        for table, source_count in sorted(source_data_tables.items()):
            target_count = target_counts_after.get(table)
            if target_count != source_count:
                mismatches.append((table, source_count, target_count))

        if mismatches:
            print("\nCOUNT MISMATCHES:")
            for table, source_count, target_count in mismatches:
                print(f"  {table}: SQLite={source_count}, PostgreSQL={target_count}")
            fail(
                f"Verification failed: {len(mismatches)} table(s) do not match. "
                "The import transaction has been rolled back only if the mismatch "
                "was detected inside the transaction; take a backup and investigate "
                "before serving traffic."
            )

        print("\nMigration verification successful.")
        print(f"Matched application tables: {len(source_data_tables)}")
        print(f"Matched application rows: {source_data_total}")
        print("Excluded regenerated/ephemeral tables:", ", ".join(sorted(EXCLUDED_TABLES)))
        return 0
    finally:
        try:
            fixture_path.unlink(missing_ok=True)
        except OSError:
            pass
        source_connection.close()
        target_connection.close()


if __name__ == "__main__":
    main()
