# Generated by Django 5.2.17 on 2026-09-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
        ('vendors', '0002_delete_vendorapplication_delete_vendorprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(name='DesignTheme'), migrations.DeleteModel(name='StorefrontMedia'), migrations.DeleteModel(name='StorefrontSection'), migrations.CreateModel(name='DesignTheme', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('is_global', models.BooleanField(default=False)), ('is_active', models.BooleanField(default=True)), ('tokens', models.JSONField(blank=True, default=dict)), ('layout', models.JSONField(blank=True, default=dict)), ('sections', models.JSONField(blank=True, default=list)), ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_themes', to=settings.AUTH_USER_MODEL)), ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='vendors.vendorprofile'))], options={'db_table': 'marketplace_designtheme', 'ordering': ['-is_global', '-updated_at']}), migrations.CreateModel(name='StorefrontSection', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(blank=True, max_length=180)), ('section_type', models.CharField(choices=[('hero', 'عرض رئيسي'), ('category', 'فئات'), ('product_grid', 'شبكة منتجات'), ('trend', 'ترند'), ('banner', 'بانر')], max_length=30)), ('config', models.JSONField(blank=True, default=dict)), ('sort_order', models.PositiveIntegerField(default=0)), ('is_visible', models.BooleanField(default=True)), ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_sections', to=settings.AUTH_USER_MODEL)), ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefront_sections', to='vendors.vendorprofile'))], options={'db_table': 'marketplace_storefrontsection', 'ordering': ['sort_order', 'id']}), migrations.CreateModel(name='StorefrontMedia', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=180)), ('image', models.ImageField(upload_to='storefront/')), ('alt_text', models.CharField(blank=True, max_length=180)), ('target_url', models.CharField(blank=True, max_length=500)), ('is_active', models.BooleanField(default=True)), ('sort_order', models.PositiveIntegerField(db_index=True, default=0)), ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefront_media', to='vendors.vendorprofile'))], options={'db_table': 'marketplace_storefrontmedia', 'ordering': ['sort_order', '-updated_at', 'id'], 'indexes': [models.Index(fields=['vendor', 'is_active'], name='marketplace_vendor__4576fa_idx')]})]
        ),
    ]
