import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { ProductCard } from "@/components/product-card";
import { getProducts, type StoreProduct } from "@/lib/product-api";
export default function CollectionScreen(){ const params=useLocalSearchParams<{category?:string;mode?:string;tag?:string}>(); const [products,setProducts]=useState<StoreProduct[]>([]); const [loading,setLoading]=useState(true); useEffect(()=>{getProducts().then(setProducts).finally(()=>setLoading(false));},[]); const title=params.category|| (params.mode==="flash"?"التخفيضات السريعة":params.mode==="free_shipping"?"الشحن المجاني":params.tag?`#${params.tag}`:"كل المنتجات"); const visible=useMemo(()=>products.filter(p=>{if(params.category)return p.categories.some(c=>c.toLowerCase()===params.category?.toLowerCase())||p.category.toLowerCase()===params.category?.toLowerCase(); if(params.mode==="flash")return p.discountPercent>0; if(params.mode==="free_shipping")return String(p.shippingNote||"").includes("مجاني")||String(p.shippingNote||"").includes("free"); if(params.tag)return p.trendTags.some(tag=>tag.toLowerCase()===params.tag?.toLowerCase()); return true;}),[products,params]); return <ScreenContainer edges={["top","bottom","left","right"]} className="bg-[#F7F7F7]"><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-forward" size={24}/></TouchableOpacity><Text style={s.title}>{title}</Text><View style={{width:24}}/></View>{loading?<View style={s.center}><ActivityIndicator color="#E60023"/></View>:<FlatList data={visible} numColumns={2} keyExtractor={item=>item.id} contentContainerStyle={s.list} columnWrapperStyle={s.row} ListHeaderComponent={<Text style={s.count}>{visible.length} صنف متاح</Text>} ListEmptyComponent={<Text style={s.empty}>لا توجد منتجات منشورة مطابقة لهذه المجموعة.</Text>} renderItem={({item})=><View style={s.item}><ProductCard product={item}/></View>}/>}</ScreenContainer>; }
const s=StyleSheet.create({header:{height:56,paddingHorizontal:16,backgroundColor:"#FFF",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontSize:18,fontWeight:"900"},list:{padding:10,paddingBottom:40},row:{gap:10,marginBottom:10},item:{flex:1,maxWidth:"48%"},count:{textAlign:"right",padding:10,color:"#777",fontSize:12},empty:{textAlign:"center",padding:40,color:"#777"},center:{flex:1,alignItems:"center",justifyContent:"center"}});
