import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import * as Sharing from "expo-sharing";
import { captureRef } from "react-native-view-shot";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { ApiClient } from "@/lib/api-client";
import { formatYER } from "@/lib/catalog";

type Transaction = { id: number; transaction_type: string; amount: string; balance_after: string; reference?: string; note?: string; metadata?: Record<string, string>; created_at: string };
type ReportData = { wallet_balance: string; total_spent: string; orders_count: number; recent_transactions: Transaction[] };
const typeLabel: Record<string, string> = { top_up: "إضافة رصيد", adjustment: "تسوية إدارية", payment: "دفع", refund: "استرداد", reward: "مكافأة", withdrawal: "سحب" };

export default function CustomerReportsScreen() { const [data, setData] = useState<ReportData | null>(null); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Transaction | null>(null); const receiptRef = useRef<View>(null);
  useEffect(() => { Promise.all([ApiClient.get<any>("/api/wallets/"), ApiClient.get<any>("/api/orders/")]).then(([walletRes, ordersRes]) => { const wallet = walletRes.results?.[0] ?? walletRes; const orders = ordersRes.results || []; const spent = orders.reduce((sum: number, order: any) => sum + Number(order.total || 0), 0); setData({ wallet_balance: String(wallet?.balance ?? "0"), total_spent: spent.toFixed(2), orders_count: orders.length, recent_transactions: wallet?.transactions ?? [] }); }).catch(() => Alert.alert("تعذر تحميل كشف الحساب", "حاولي تحديث الصفحة." )).finally(() => setLoading(false)); }, []);
  async function saveReceipt() { if (!receiptRef.current || !selected) return; try { const uri = await captureRef(receiptRef, { format: "png", quality: 0.95 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "image/png", dialogTitle: "حفظ إيصال العملية" }); else await Share.share({ message: `إيصال ${typeLabel[selected.transaction_type] || selected.transaction_type}\nالمبلغ: ${selected.amount}\nالرصيد بعد العملية: ${selected.balance_after}\nالمرجع: ${selected.reference || "-"}` }); } catch { Alert.alert("تعذر الحفظ", "يمكنك أخذ لقطة شاشة للإيصال."); } }
  if (loading) return <ScreenContainer><View style={s.center}><ActivityIndicator color="#E60023" /></View></ScreenContainer>;
  return <ScreenContainer edges={["top","bottom","left","right"]} className="bg-[#F5F5F5]"><View style={s.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={25} /></TouchableOpacity><Text style={s.title}>كشف الحساب والعمليات</Text><View style={{width:25}} /></View><FlatList data={data?.recent_transactions ?? []} keyExtractor={item => String(item.id)} contentContainerStyle={s.content} ListHeaderComponent={<><View style={s.summaryRow}><View style={s.summaryCard}><Text style={s.label}>الرصيد الحالي</Text><Text style={s.balance}>{formatYER(Number(data?.wallet_balance ?? 0))}</Text><Text style={s.currency}>الرصيد من الخادم مباشرة</Text></View><View style={s.summaryCard}><Text style={s.label}>إجمالي المشتريات</Text><Text style={[s.balance,{color:"#E60023"}]}>{formatYER(Number(data?.total_spent ?? 0))}</Text></View></View><View style={s.singleCard}><Text style={s.label}>عدد الطلبات</Text><Text style={s.balance}>{data?.orders_count ?? 0} طلب</Text></View><Text style={s.sectionTitle}>كل العمليات المالية</Text></>} ListEmptyComponent={<Text style={s.empty}>لا توجد عمليات مسجلة حتى الآن.</Text>} renderItem={({item}) => <TouchableOpacity style={s.transaction} onPress={() => setSelected(item)}><View style={s.icon}><MaterialIcons name={Number(item.amount) >= 0 ? "add-circle" : "remove-circle"} size={24} color={Number(item.amount) >= 0 ? "#168451" : "#E60023"} /></View><View style={s.transCopy}><Text style={s.transNote}>{item.note || typeLabel[item.transaction_type] || item.transaction_type}</Text><Text style={s.transDate}>{new Date(item.created_at).toLocaleString("ar-YE")}</Text></View><View style={s.transAmountBox}><Text style={[s.transAmount,{color:Number(item.amount)>=0?"#168451":"#E60023"}]}>{Number(item.amount)>=0?"+":""}{item.amount}</Text><Text style={s.transBalance}>الرصيد: {item.balance_after}</Text></View></TouchableOpacity>} />{selected ? <View style={s.modalBackdrop}><View ref={receiptRef} collapsable={false} style={s.receipt}><Text style={s.receiptBrand}>شبيك</Text><Text style={s.receiptTitle}>إيصال عملية مالية</Text><Text style={s.receiptType}>{typeLabel[selected.transaction_type] || selected.transaction_type}</Text><Text style={s.receiptAmount}>{selected.amount} ر.ي</Text><Text style={s.receiptLine}>الرصيد بعد العملية: {selected.balance_after} ر.ي</Text><Text style={s.receiptLine}>المرجع: {selected.reference || "غير متوفر"}</Text><Text style={s.receiptLine}>التاريخ: {new Date(selected.created_at).toLocaleString("ar-YE")}</Text><View style={s.modalActions}><TouchableOpacity onPress={saveReceipt} style={s.saveBtn}><Text style={s.saveText}>حفظ كصورة</Text></TouchableOpacity><TouchableOpacity onPress={() => setSelected(null)} style={s.cancelBtn}><Text>إغلاق</Text></TouchableOpacity></View></View></View> : null}</ScreenContainer>;
}
const s=StyleSheet.create({header:{padding:16,backgroundColor:"#FFF",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontSize:18,fontWeight:"900"},content:{padding:14,paddingBottom:50},summaryRow:{flexDirection:"row-reverse",gap:10,marginBottom:10},summaryCard:{flex:1,backgroundColor:"#FFF",padding:16,borderRadius:10,alignItems:"center"},label:{color:"#777",fontSize:12,marginBottom:6},balance:{fontSize:18,fontWeight:"900",color:"#111"},currency:{fontSize:9,color:"#999",marginTop:4},singleCard:{backgroundColor:"#FFF",padding:16,borderRadius:10,alignItems:"center",marginBottom:20},sectionTitle:{fontSize:17,fontWeight:"900",textAlign:"right",marginBottom:12},transaction:{backgroundColor:"#FFF",padding:13,borderRadius:9,flexDirection:"row-reverse",alignItems:"center",gap:10,marginBottom:8},icon:{width:32},transCopy:{flex:1,alignItems:"flex-end"},transNote:{fontSize:13,fontWeight:"800",textAlign:"right"},transDate:{color:"#888",fontSize:10,marginTop:4,textAlign:"right"},transAmountBox:{alignItems:"flex-start"},transAmount:{fontSize:15,fontWeight:"900"},transBalance:{color:"#666",fontSize:10,marginTop:4},empty:{textAlign:"center",color:"#777",marginTop:20},center:{flex:1,justifyContent:"center",alignItems:"center"},modalBackdrop:{position:"absolute",inset:0,backgroundColor:"rgba(0,0,0,.55)",justifyContent:"center",padding:22},receipt:{backgroundColor:"#FFF",borderRadius:14,padding:22,alignItems:"flex-end"},receiptBrand:{fontSize:12,color:"#E60023",fontWeight:"900"},receiptTitle:{fontSize:19,fontWeight:"900",marginTop:8},receiptType:{color:"#666",marginTop:18},receiptAmount:{fontSize:26,fontWeight:"900",color:"#168451",marginTop:8},receiptLine:{fontSize:12,color:"#333",marginTop:10,textAlign:"right"},modalActions:{flexDirection:"row-reverse",gap:10,marginTop:20},saveBtn:{backgroundColor:"#111",padding:12,borderRadius:8},saveText:{color:"#FFF",fontWeight:"800"},cancelBtn:{padding:12,borderWidth:1,borderColor:"#DDD",borderRadius:8}});
