import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Linking from "expo-linking";
import { ActivityIndicator, Alert, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { apiCall } from "@/lib/_core/api";
type Referral = { isEnabled: boolean; code: string; invitedCount: number };
export default function InviteScreen() { const [referral, setReferral] = useState<Referral | null>(null); useEffect(() => { apiCall<{ referral: Referral }>("/api/referrals/me").then((data) => setReferral(data.referral)).catch(() => setReferral(null)); }, []); const share = async () => { if (!referral) return; const url = Linking.createURL("/register", { queryParams: { ref: referral.code } }); try { await Share.share({ message: `انضم/ي إلى التخفيض الصح من رابط دعوتي واحصل/ي على عروض مميزة: ${url}` }); } catch { Alert.alert("تعذر المشاركة", "حاولي مجددًا."); } }; if (!referral) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-white"><View style={styles.center}><ActivityIndicator color="#E60023" /></View></ScreenContainer>; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><Text style={styles.title}>دعوة الأصدقاء</Text><View style={{ width: 23 }} /></View>{referral.isEnabled ? <View style={styles.card}><View style={styles.icon}><MaterialIcons name="share" size={30} color="#FFF" /></View><Text style={styles.heading}>شارك رابطك الخاص</Text><Text style={styles.copy}>كل مستخدم يسجّل من رابطك يُحتسب ضمن دعواتك، ويمكن للإدارة منحك قسائم أو رصيدًا.</Text><View style={styles.count}><Text style={styles.countNumber}>{referral.invitedCount}</Text><Text style={styles.countLabel}>مستخدمون من دعوتك</Text></View><TouchableOpacity style={styles.share} onPress={share}><MaterialIcons name="ios-share" size={20} color="#FFF" /><Text style={styles.shareText}>مشاركة رابط الدعوة</Text></TouchableOpacity></View> : <View style={styles.disabled}><MaterialIcons name="lock-outline" size={38} color="#999" /><Text style={styles.disabledTitle}>الدعوات غير مفعّلة الآن</Text><Text style={styles.copy}>سيظهر زر المشاركة هنا عندما تفعّله الإدارة.</Text></View>}</ScreenContainer>; }
const styles = StyleSheet.create({ header: { height: 56, backgroundColor: "#FFF", paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 16, fontWeight: "900" }, card: { margin: 14, backgroundColor: "#FFF", padding: 23, alignItems: "center" }, icon: { width: 62, height: 62, borderRadius: 31, backgroundColor: "#E60023", justifyContent: "center", alignItems: "center" }, heading: { fontSize: 19, fontWeight: "900", marginTop: 14 }, copy: { color: "#777", fontSize: 11, textAlign: "center", lineHeight: 18, marginTop: 7 }, count: { marginTop: 21, alignItems: "center" }, countNumber: { fontSize: 31, fontWeight: "900", color: "#E60023" }, countLabel: { fontSize: 10, color: "#666" }, share: { width: "100%", height: 50, marginTop: 24, backgroundColor: "#171717", flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 }, shareText: { color: "#FFF", fontWeight: "900" }, disabled: { alignItems: "center", padding: 42 }, disabledTitle: { fontWeight: "900", marginTop: 12 }, center: { flex: 1, alignItems: "center", justifyContent: "center" } });
