import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";

import { formatYER } from "@/lib/catalog";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { getMyOrders, type StoreOrder } from "@/lib/order-api";

export default function OrdersScreen() { const { isAuthenticated } = useAuth(); const [orders, setOrders] = useState<StoreOrder[]>([]); const [loading, setLoading] = useState(true); const load = async () => { try { setLoading(true); setOrders(await getMyOrders()); } finally { setLoading(false); } }; useEffect(() => { if (isAuthenticated) load(); else setLoading(false); }, [isAuthenticated]); if (!isAuthenticated) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-white"><View style={styles.empty}><MaterialIcons name="lock-outline" size={38} color="#E60023" /><Text style={styles.emptyTitle}>سجّلي الدخول لرؤية طلباتك</Text><TouchableOpacity style={styles.login} onPress={() => router.push("/login" as never)}><Text style={styles.loginText}>تسجيل الدخول</Text></TouchableOpacity></View></ScreenContainer>; return <ScreenContainer edges={["top", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><Text style={styles.title}>طلباتي</Text><View style={{ width: 23 }} /></View><FlatList data={orders} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshing={loading} onRefresh={load} renderItem={({ item }) => <TouchableOpacity style={styles.order} onPress={() => router.push(`/order-chat/${item.id}` as never)}><View style={styles.top}><Text style={[styles.status, item.status === "paid_shipping" && styles.done]}>{item.statusLabel}</Text><Text style={styles.number}>#{item.orderCode}</Text></View><View style={styles.divider} /><View style={styles.bottom}><Text style={styles.total}>{formatYER(item.totalAmount)}</Text><Text style={styles.date}>{item.items.length} أصناف · {new Date(item.createdAt).toLocaleDateString("ar-YE")}</Text></View><View style={styles.track}><View style={[styles.trackActive, item.status === "paid_shipping" && styles.trackDone, { width: item.status === "paid_shipping" ? "100%" : item.status === "payment_proof_sent" ? "66%" : "33%" }]} /></View></TouchableOpacity>} ListHeaderComponent={<View style={styles.banner}><MaterialIcons name="receipt-long" size={24} color="#E60023" /><View style={styles.bannerCopy}><Text style={styles.bannerTitle}>تابعي طلباتك بسهولة</Text><Text style={styles.bannerText}>كل طلب يفتح دردشة خاصة بك مع فريق المتجر.</Text></View></View>} ListEmptyComponent={loading ? <ActivityIndicator color="#E60023" style={{ marginTop: 35 }} /> : <View style={styles.empty}><MaterialIcons name="receipt-long" size={42} color="#9D9D9D" /><Text style={styles.emptyTitle}>لا توجد طلبات بعد</Text><Text style={styles.emptyText}>أكملي طلبًا من الحقيبة لفتح محادثة خاصة.</Text></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { height: 54, backgroundColor: "#FFFFFF", paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderColor: "#EAEAEA" }, title: { color: "#171717", fontWeight: "900", fontSize: 16 }, list: { padding: 12 }, banner: { backgroundColor: "#FDECEF", padding: 13, flexDirection: "row-reverse", gap: 10, alignItems: "center", marginBottom: 10 }, bannerCopy: { flex: 1, alignItems: "flex-end" }, bannerTitle: { color: "#57111D", fontSize: 13, fontWeight: "900" }, bannerText: { color: "#8A5560", fontSize: 10, marginTop: 3, textAlign: "right" }, order: { backgroundColor: "#FFFFFF", padding: 14, marginBottom: 9 }, top: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, status: { color: "#C77900", fontSize: 12, fontWeight: "900" }, done: { color: "#168451" }, number: { color: "#222222", fontSize: 12, fontWeight: "800" }, divider: { height: 1, backgroundColor: "#EDEDED", marginVertical: 11 }, bottom: { flexDirection: "row-reverse", justifyContent: "space-between" }, total: { color: "#171717", fontSize: 14, fontWeight: "900" }, date: { color: "#777777", fontSize: 11 }, track: { height: 3, backgroundColor: "#ECECEC", marginTop: 12, width: "100%" }, trackActive: { height: "100%", backgroundColor: "#E60023" }, trackDone: { backgroundColor: "#168451" }, empty: { alignItems: "center", justifyContent: "center", padding: 34, gap: 9 }, emptyTitle: { color: "#313131", fontSize: 14, fontWeight: "900", textAlign: "center" }, emptyText: { color: "#777777", fontSize: 11, textAlign: "center" }, login: { backgroundColor: "#171717", paddingHorizontal: 22, paddingVertical: 12, marginTop: 4 }, loginText: { color: "#FFFFFF", fontWeight: "800" },
});
