import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { apiCall } from "@/lib/_core/api";
import { useAuth } from "@/hooks/use-auth";
const labels = { YER: "ريال يمني", SAR: "ريال سعودي", USD: "دولار" } as const;
export default function SettingsScreen() { const { user } = useAuth(); const [currency, setCurrency] = useState<keyof typeof labels>("YER"); useEffect(() => { apiCall<{ currency: keyof typeof labels }>("/api/preferences").then((data) => setCurrency(data.currency)).catch(() => undefined); }, []); const switchCurrency = async () => { const next = currency === "YER" ? "SAR" : currency === "SAR" ? "USD" : "YER"; try { await apiCall("/api/preferences", { method: "PATCH", body: JSON.stringify({ currency: next }) }); setCurrency(next); } catch { Alert.alert("تعذر حفظ العملة", "سجّلي الدخول ثم حاولي مجددًا."); } }; return <ScreenContainer edges={["top", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><Text style={styles.title}>الإعدادات</Text><View style={{ width: 23 }} /></View><View style={styles.section}><Row icon="payments" label="العملة" value={labels[currency]} onPress={switchCurrency} /><Row icon="support-agent" label="تواصل معنا" value="دردشة خاصة مع الإدارة" onPress={() => router.push("/support" as never)} /><Row icon="language" label="اللغة" value="العربية" onPress={() => Alert.alert("اللغة", "واجهة المتجر عربية باتجاه RTL.")} /></View>{user?.role === "admin" ? <View style={styles.section}><Row icon="payments" label="التحكم بالأسعار" value="المحافظات خارج إب" onPress={() => router.push("/admin/pricing" as never)} /></View> : null}<Text style={styles.version}>التخفيض الصح · إصدار 1.0.0</Text></ScreenContainer>; }
function Row({ icon, label, value, onPress }: { icon: "payments" | "support-agent" | "language"; label: string; value: string; onPress: () => void }) { return <TouchableOpacity style={styles.row} onPress={onPress}><MaterialIcons name="chevron-left" size={22} color="#939393" /><View style={styles.copy}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View><MaterialIcons name={icon} size={21} color="#242424" /></TouchableOpacity>; }
const styles = StyleSheet.create({ header: { height: 56, backgroundColor: "#FFF", paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 16, fontWeight: "900" }, section: { backgroundColor: "#FFF", marginTop: 11 }, row: { minHeight: 64, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderColor: "#F0F0F0" }, copy: { flex: 1, alignItems: "flex-end" }, label: { fontSize: 14, fontWeight: "800" }, value: { color: "#777", fontSize: 10, marginTop: 3 }, version: { textAlign: "center", color: "#999", fontSize: 10, marginTop: 22 } });
