import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ActivityIndicator, Alert, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { apiCall } from "@/lib/_core/api";
import { useAuth } from "@/hooks/use-auth";

type Employee={id:number;name:string;role:string;avatar?:string|null}; type Message={id:number;senderRole:"customer"|"admin";senderName:string;body:string;createdAt:string}; type Conversation={id:number;subject:string;isClosed:boolean;messages:Message[]}; type ResponseData={conversation:Conversation;employees:Employee[]};
export default function SupportScreen(){
 const {isAuthenticated}=useAuth(); const [data,setData]=useState<ResponseData|null>(null); const [draft,setDraft]=useState(""); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{setLoading(true);setData(await apiCall<ResponseData>("/api/support/"));}catch(error){if(isAuthenticated)Alert.alert("تعذر فتح الدعم",error instanceof Error?error.message:"حاول مجددًا.");}finally{setLoading(false);}},[isAuthenticated]); useEffect(()=>{if(isAuthenticated)load();},[isAuthenticated,load]);
 async function send(){const body=draft.trim();if(!body)return;try{const result=await apiCall<ResponseData>("/api/support/messages/",{method:"POST",body:JSON.stringify({body})});setData(result);setDraft("");}catch(error){Alert.alert("تعذر إرسال الرسالة",error instanceof Error?error.message:"حاول مجددًا.");}}
 if(!isAuthenticated)return <ScreenContainer edges={["top","bottom","left","right"]} className="bg-white"><View style={styles.center}><Text>سجّل الدخول للتواصل مع الإدارة.</Text><TouchableOpacity style={styles.login} onPress={()=>router.push("/login" as never)}><Text style={styles.white}>تسجيل الدخول</Text></TouchableOpacity></View></ScreenContainer>;
 if(loading||!data)return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#E60023"/></View></ScreenContainer>;
 return <ScreenContainer edges={["top","bottom","left","right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717"/></TouchableOpacity><View><Text style={styles.title}>تواصل معنا</Text><Text style={styles.sub}>{data.conversation.isClosed?"المحادثة مغلقة وستفتح برسالة جديدة":"الدعم والإدارة"}</Text></View><View style={{width:23}}/></View><View style={styles.staff}><View style={styles.staffHeader}><Text style={styles.staffTitle}>فريق الإدارة</Text><MaterialIcons name="groups" size={18} color="#E60023"/></View><View style={styles.staffRow}>{data.employees.slice(0,5).map(employee=><View key={employee.id} style={styles.employee}><View style={styles.avatar}><MaterialIcons name="person" size={17} color="#666"/></View><Text numberOfLines={1} style={styles.employeeName}>{employee.name}</Text><Text style={styles.employeeRole}>{employee.role}</Text></View>)}</View></View><FlatList data={data.conversation.messages} keyExtractor={item=>String(item.id)} contentContainerStyle={styles.list} onRefresh={load} refreshing={loading} renderItem={({item})=><View style={[styles.row,item.senderRole==="customer"&&styles.ownRow]}><View style={[styles.bubble,item.senderRole==="customer"?styles.own:styles.admin]}><Text style={[styles.sender,item.senderRole==="customer"&&styles.white]}>{item.senderName}</Text><Text style={[styles.message,item.senderRole==="customer"&&styles.white]}>{item.body}</Text><Text style={[styles.time,item.senderRole==="customer"&&styles.ownTime]}>{new Date(item.createdAt).toLocaleTimeString("ar-YE",{hour:"2-digit",minute:"2-digit"})}</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="support-agent" size={36} color="#999"/><Text style={styles.emptyText}>أرسل استفسارك وسيظهر الرد هنا.</Text></View>}/><View style={styles.composer}><TextInput style={styles.input} value={draft} onChangeText={setDraft} placeholder="اكتب رسالتك للإدارة" placeholderTextColor="#888" textAlign="right" onSubmitEditing={send}/><TouchableOpacity style={styles.send} onPress={send} disabled={!draft.trim()}><MaterialIcons name="send" color="#FFF" size={19}/></TouchableOpacity></View></ScreenContainer>;
}
const styles=StyleSheet.create({header:{height:58,backgroundColor:"#FFF",paddingHorizontal:15,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontWeight:"900",fontSize:15,textAlign:"center",color:"#171717"},sub:{color:"#777",fontSize:9,textAlign:"center",marginTop:2},staff:{backgroundColor:"#FFF",padding:12,borderBottomWidth:1,borderColor:"#EEE"},staffHeader:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between"},staffTitle:{fontSize:12,fontWeight:"900",color:"#222"},staffRow:{flexDirection:"row-reverse",gap:10,marginTop:9},employee:{width:62,alignItems:"center"},avatar:{width:36,height:36,borderRadius:18,backgroundColor:"#F3F3F3",alignItems:"center",justifyContent:"center"},employeeName:{fontSize:8,fontWeight:"800",color:"#333",marginTop:3},employeeRole:{fontSize:7,color:"#999",marginTop:2},list:{padding:12},row:{alignItems:"flex-end",marginBottom:8},ownRow:{alignItems:"flex-start"},bubble:{maxWidth:"80%",padding:10,borderRadius:13},own:{backgroundColor:"#171717"},admin:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#EEE"},sender:{fontSize:8,fontWeight:"900",color:"#777",marginBottom:3,textAlign:"right"},message:{fontSize:12,textAlign:"right",color:"#222",lineHeight:18},white:{color:"#FFF"},time:{fontSize:7,color:"#999",marginTop:4,textAlign:"right"},ownTime:{color:"#CCC"},composer:{flexDirection:"row-reverse",gap:8,padding:9,backgroundColor:"#FFF",borderTopWidth:1,borderColor:"#E6E6E6"},input:{flex:1,height:42,backgroundColor:"#F1F1F1",paddingHorizontal:12,borderRadius:21},send:{width:42,height:42,borderRadius:21,backgroundColor:"#E60023",alignItems:"center",justifyContent:"center"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:12,padding:24},login:{backgroundColor:"#171717",padding:12},empty:{alignItems:"center",padding:28},emptyText:{color:"#777",marginTop:8}});
