import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ActivityIndicator, Alert, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { apiCall } from "@/lib/_core/api";
import { useAuth } from "@/hooks/use-auth";
type Conversation = { id: number; messages: { id: number; senderRole: "customer" | "admin"; body: string; createdAt: string }[] };
export default function SupportScreen() { const { isAuthenticated } = useAuth(); const [data, setData] = useState<Conversation | null>(null); const [draft, setDraft] = useState(""); const [loading, setLoading] = useState(true); const load = useCallback(async () => { try { setData((await apiCall<{ conversation: Conversation }>("/api/support")).conversation); } catch (error) { Alert.alert("تعذر فتح المحادثة", error instanceof Error ? error.message : "سجّلي الدخول أولًا."); } finally { setLoading(false); } }, []); useEffect(() => { if (isAuthenticated) load(); }, [isAuthenticated, load]); const send = async () => { if (!draft.trim()) return; try { setData((await apiCall<{ conversation: Conversation }>("/api/support/messages", { method: "POST", body: JSON.stringify({ body: draft }) })).conversation); setDraft(""); } catch (error) { Alert.alert("تعذر الإرسال", error instanceof Error ? error.message : "حاولي مجددًا."); } }; if (!isAuthenticated) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-white"><View style={styles.center}><Text>سجّلي الدخول للتواصل مع الإدارة.</Text><TouchableOpacity style={styles.login} onPress={() => router.push("/login" as never)}><Text style={styles.white}>تسجيل الدخول</Text></TouchableOpacity></View></ScreenContainer>; if (loading || !data) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-white"><View style={styles.center}><ActivityIndicator color="#E60023" /></View></ScreenContainer>; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="bg-[#F6F6F6]"><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="#171717" /></TouchableOpacity><View><Text style={styles.title}>تواصل معنا</Text><Text style={styles.sub}>محادثة خاصة مع الإدارة</Text></View><View style={{ width: 23 }} /></View><FlatList data={data.messages} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={[styles.row, item.senderRole === "customer" && styles.ownRow]}><View style={[styles.bubble, item.senderRole === "customer" ? styles.own : styles.admin]}><Text style={[styles.message, item.senderRole === "customer" && styles.white]}>{item.body}</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="support-agent" size={36} color="#999" /><Text style={styles.emptyText}>أرسلي استفسارك، وسترد الإدارة هنا.</Text></View>} /><View style={styles.composer}><TextInput style={styles.input} value={draft} onChangeText={setDraft} placeholder="اكتبي رسالتك" textAlign="right" onSubmitEditing={send} /><TouchableOpacity style={styles.send} onPress={send}><MaterialIcons name="send" color="#FFF" size={19} /></TouchableOpacity></View></ScreenContainer>; }
const styles = StyleSheet.create({ header: { height: 58, backgroundColor: "#FFF", paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontWeight: "900", fontSize: 15, textAlign: "center" }, sub: { color: "#777", fontSize: 9, textAlign: "center" }, list: { padding: 12 }, row: { alignItems: "flex-end", marginBottom: 8 }, ownRow: { alignItems: "flex-start" }, bubble: { maxWidth: "80%", padding: 10 }, own: { backgroundColor: "#171717" }, admin: { backgroundColor: "#FFF" }, message: { fontSize: 12, textAlign: "right" }, white: { color: "#FFF" }, composer: { flexDirection: "row-reverse", gap: 8, padding: 9, backgroundColor: "#FFF" }, input: { flex: 1, height: 42, backgroundColor: "#F1F1F1", paddingHorizontal: 10, writingDirection: "rtl" }, send: { width: 42, height: 42, backgroundColor: "#E60023", alignItems: "center", justifyContent: "center" }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 }, login: { backgroundColor: "#171717", padding: 12 }, empty: { alignItems: "center", padding: 28 }, emptyText: { color: "#777", marginTop: 8 } });
