import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { ApiClient } from "@/lib/api-client";

type Vendor = { id: number; store_name: string; slug: string; description?: string; logo_url?: string | null; cover_url?: string | null; status: string };
export default function VendorsScreen() { const [query,setQuery]=useState(""); const [vendors,setVendors]=useState<Vendor[]>([]); const [loading,setLoading]=useState(true); async function load(value="") { try { setLoading(true); const data=await ApiClient.get<{results?:Vendor[]}>(`/api/vendors/${value?`?q=${encodeURIComponent(value)}`:""}`); setVendors(data.results ?? []); } finally { setLoading(false); } } useEffect(()=>{load();},[]); return <ScreenContainer edges={["top","bottom","left","right"]} className="bg-[#F6F6F6]"><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-forward" size={24}/></TouchableOpacity><Text style={s.title}>التجار والمتاجر</Text><View style={{width:24}}/></View><View style={s.search}><MaterialIcons name="search" size={22} color="#777"/><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>load(query)} placeholder="ابحثي عن اسم التاجر أو المتجر" textAlign="right" style={s.input}/></View>{loading?<View style={s.center}><ActivityIndicator color="#E60023"/></View>:<FlatList data={vendors} keyExtractor={item=>String(item.id)} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>لا توجد متاجر مطابقة.</Text>} renderItem={({item})=><TouchableOpacity style={s.card} onPress={()=>router.push(`/store/${item.slug}` as never)}><View style={s.copy}><Text style={s.name}>{item.store_name}</Text><View style={s.rating}><MaterialIcons name="star" size={16} color="#F2B600"/><Text style={s.ratingText}>4.8 · متجر موثوق</Text></View><Text style={s.description}>{item.description || "وصف المتجر ومنتجاته"}</Text><Text style={s.open}>عرض المتجر والمنتجات ←</Text></View>{item.logo_url?<Image source={{uri:item.logo_url}} style={s.logo}/>:<View style={s.logo}><MaterialIcons name="storefront" size={30} color="#E60023"/></View>}</TouchableOpacity>}/>}</ScreenContainer>; }
const s=StyleSheet.create({header:{height:58,paddingHorizontal:16,backgroundColor:"#FFF",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontSize:18,fontWeight:"900"},search:{margin:12,paddingHorizontal:12,height:48,borderRadius:10,backgroundColor:"#FFF",flexDirection:"row-reverse",alignItems:"center",gap:8},input:{flex:1,fontSize:13,color:"#111"},list:{padding:12,paddingTop:0},card:{backgroundColor:"#FFF",borderRadius:12,padding:14,marginBottom:10,flexDirection:"row-reverse",gap:12,alignItems:"center"},logo:{width:64,height:64,borderRadius:32,backgroundColor:"#F7F7F7",alignItems:"center",justifyContent:"center",overflow:"hidden"},copy:{flex:1,alignItems:"flex-end"},name:{fontSize:16,fontWeight:"900"},rating:{flexDirection:"row",alignItems:"center",gap:4,marginTop:4},ratingText:{fontSize:11,color:"#777"},description:{fontSize:11,color:"#777",marginTop:6,textAlign:"right"},open:{fontSize:11,color:"#E60023",fontWeight:"800",marginTop:8},empty:{textAlign:"center",color:"#777",padding:40},center:{flex:1,alignItems:"center",justifyContent:"center"}});
