import { ActivityIndicator, FlatList, Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { ApiClient } from "@/lib/api-client";

type Vendor={id:number;store_name:string;slug:string;description?:string;logo_url?:string|null;cover_url?:string|null;status:string};
type VendorPage={results?:Vendor[];next?:string|null};
async function loadAllVendors(query:string){const all:Vendor[]=[];for(let page=1;page<=50;page++){const params=new URLSearchParams({page:String(page)});if(query.trim())params.set("q",query.trim());const data=await ApiClient.get<VendorPage|Vendor[]>(`/api/vendors/?${params.toString()}`);if(Array.isArray(data)){all.push(...data);break}all.push(...(data.results??[]));if(!data.next||!(data.results??[]).length)break}return all.filter(v=>v.status==="active")}
export default function VendorsScreen(){const [query,setQuery]=useState("");const [vendors,setVendors]=useState<Vendor[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");async function load(value=""){try{setLoading(true);setError("");setVendors(await loadAllVendors(value))}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل المتاجر.")}finally{setLoading(false)}}useEffect(()=>{load()},[]);return <ScreenContainer edges={["top","bottom","left","right"]} className="bg-[#F4F5F7]"><View style={s.header}><TouchableOpacity onPress={()=>router.back()} style={s.icon}><MaterialIcons name="arrow-forward" size={24} color="#111"/></TouchableOpacity><View style={s.headerCopy}><Text style={s.title}>المتاجر</Text><Text style={s.subtitle}>اكتشف المتاجر النشطة ومنتجاتها</Text></View><View style={{width:42}}/></View><View style={s.searchWrap}><MaterialIcons name="search" size={21} color="#777"/><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>load(query)} placeholder="ابحث باسم المتجر" placeholderTextColor="#999" textAlign="right" style={s.input} returnKeyType="search"/></View>{loading?<View style={s.center}><ActivityIndicator size="large" color="#E11D48"/><Text style={s.loading}>جارٍ تحميل المتاجر...</Text></View>:error?<View style={s.center}><MaterialIcons name="error-outline" size={38} color="#E11D48"/><Text style={s.emptyText}>{error}</Text><TouchableOpacity style={s.retry} onPress={()=>load(query)}><Text style={s.retryText}>إعادة المحاولة</Text></TouchableOpacity></View>:<FlatList data={vendors} keyExtractor={item=>String(item.id)} contentContainerStyle={s.list} showsVerticalScrollIndicator={false} ListEmptyComponent={<View style={s.empty}><MaterialIcons name="storefront" size={42} color="#C5C6CA"/><Text style={s.emptyTitle}>لا توجد متاجر مطابقة</Text><Text style={s.emptyText}>جرّب كلمة بحث مختلفة.</Text></View>} renderItem={({item})=><TouchableOpacity style={s.card} activeOpacity={0.88} onPress={()=>router.push(`/store/${item.slug}` as never)}><View style={s.cover}>{item.cover_url?<Image source={{uri:item.cover_url}} style={s.coverImage}/>:<View style={s.coverFallback}><MaterialIcons name="storefront" size={26} color="#E11D48"/></View>}<View style={s.logo}>{item.logo_url?<Image source={{uri:item.logo_url}} style={s.logoImage}/>:<MaterialIcons name="storefront" size={23} color="#E11D48"/>}</View></View><View style={s.body}><Text style={s.name}>{item.store_name}</Text><Text style={s.description}>{item.description||"متجر متاح للتصفح والشراء."}</Text><View style={s.footer}><Text style={s.open}>فتح المتجر</Text><MaterialIcons name="arrow-back" size={16} color="#E11D48"/></View></View></TouchableOpacity>}/>}</ScreenContainer>}
const s=StyleSheet.create({header:{height:70,paddingHorizontal:14,backgroundColor:"#FFF",flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderColor:"#E9E9EB"},icon:{width:40,height:40,borderRadius:12,backgroundColor:"#F5F5F6",alignItems:"center",justifyContent:"center"},headerCopy:{flex:1,alignItems:"flex-end",marginHorizontal:10},title:{fontSize:19,fontWeight:"900",color:"#111"},subtitle:{fontSize:9,color:"#888",marginTop:3},searchWrap:{height:48,margin:12,backgroundColor:"#FFF",borderRadius:14,paddingHorizontal:13,flexDirection:"row-reverse",alignItems:"center",gap:8,borderWidth:1,borderColor:"#E7E7EA"},input:{flex:1,fontSize:12,color:"#111"},list:{padding:12,paddingTop:0,paddingBottom:100},card:{backgroundColor:"#FFF",borderRadius:17,overflow:"hidden",marginBottom:12,borderWidth:1,borderColor:"#E8E8EA"},cover:{height:135,position:"relative",backgroundColor:"#F3F3F4"},coverImage:{width:"100%",height:"100%"},coverFallback:{flex:1,alignItems:"center",justifyContent:"center"},logo:{position:"absolute",bottom:-25,right:14,width:56,height:56,borderRadius:18,backgroundColor:"#FFF",borderWidth:2,borderColor:"#FFF",shadowColor:"#000",shadowOpacity:0.08,shadowRadius:8,elevation:2,alignItems:"center",justifyContent:"center",overflow:"hidden"},logoImage:{width:"100%",height:"100%"},body:{padding:13,paddingTop:32,alignItems:"flex-end"},name:{fontSize:17,fontWeight:"900",color:"#111"},description:{fontSize:10,color:"#777",lineHeight:17,textAlign:"right",marginTop:5},footer:{marginTop:11,paddingTop:9,borderTopWidth:1,borderColor:"#F0F0F1",width:"100%",flexDirection:"row-reverse",justifyContent:"flex-start",alignItems:"center",gap:4},open:{fontSize:10,fontWeight:"900",color:"#E11D48"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:8,padding:30},loading:{fontSize:11,color:"#888"},empty:{alignItems:"center",paddingTop:70,paddingHorizontal:30},emptyTitle:{fontSize:15,fontWeight:"900",color:"#333",marginTop:8},emptyText:{fontSize:10,color:"#888",marginTop:4,textAlign:"center",lineHeight:18},retry:{backgroundColor:"#111",paddingHorizontal:18,paddingVertical:10,borderRadius:20},retryText:{color:"#FFF",fontWeight:"800"}});
