import type { Express, Request, Response } from "express";

import * as db from "./db";
import { sdk } from "./_core/sdk";

async function requireAdmin(req: Request, res: Response) { try { const user = await sdk.authenticateRequest(req); if (user.role !== "admin") { res.status(403).json({ error: "هذه العملية مخصصة للمدير." }); return undefined; } return user; } catch { res.status(401).json({ error: "سجّلي الدخول بحساب المدير أولًا." }); return undefined; } }
async function requireCustomer(req: Request, res: Response) { try { return await sdk.authenticateRequest(req); } catch { res.status(401).json({ error: "سجّلي الدخول أولًا لاستخدام كوبوناتك." }); return undefined; } }
export function sanitizeReward(body: Record<string, unknown>): db.CustomerRewardInput {
  const rewardType = body.rewardType; const discountType = body.discountType; const title = typeof body.title === "string" ? body.title.trim() : ""; const couponCode = typeof body.couponCode === "string" ? body.couponCode.trim().toUpperCase() : ""; const rewardTypes = ["gift", "coupon", "order_threshold", "quantity_threshold"] as const; const discountTypes = ["fixed", "percent"] as const;
  if (!title || !rewardTypes.includes(rewardType as typeof rewardTypes[number])) throw new Error("اختاري نوع الحافز وأدخلي عنوانًا له."); if (!discountTypes.includes(discountType as typeof discountTypes[number])) throw new Error("اختاري نوع الخصم."); const discountValue = Math.max(0, Number(body.discountValue) || 0); const minimumOrderAmount = Math.max(0, Number(body.minimumOrderAmount) || 0); const minimumQuantity = Math.max(0, Number(body.minimumQuantity) || 0); if (discountType === "percent" && discountValue > 90) throw new Error("لا يمكن أن يتجاوز الخصم 90%."); if (rewardType === "coupon" && !couponCode) throw new Error("أدخلي رمز الكوبون ليستخدمه العميل."); if (rewardType !== "gift" && discountValue <= 0) throw new Error("أدخلي قيمة خصم صحيحة.");
  return { rewardType: rewardType as db.CustomerRewardInput["rewardType"], title, couponCode: couponCode || undefined, discountType: discountType as db.CustomerRewardInput["discountType"], discountValue, minimumOrderAmount, minimumQuantity, giftName: typeof body.giftName === "string" ? body.giftName.trim() : "", isActive: body.isActive !== false };
}
export function registerCustomerRoutes(app: Express) {
  app.get("/api/customer/rewards", async (req, res) => { const user = await requireCustomer(req, res); if (!user) return; res.json({ rewards: await db.listActiveCustomerRewards(user.id) }); });
  app.post("/api/customer/rewards/validate", async (req, res) => { const user = await requireCustomer(req, res); if (!user) return; try { const code = typeof req.body?.code === "string" ? req.body.code.trim().toUpperCase() : ""; if (!code) throw new Error("أدخلي رمز الكوبون."); const reward = await db.validateCustomerCoupon(user.id, code, Math.max(0, Number(req.body?.orderAmount) || 0), Math.max(0, Number(req.body?.quantity) || 0)); res.json({ reward }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "تعذر استخدام الكوبون." }); } });
  app.get("/api/admin/customers", async (req, res) => { if (!await requireAdmin(req, res)) return; res.json({ customers: await db.listCustomers(typeof req.query.governorate === "string" ? req.query.governorate : undefined) }); });
  app.get("/api/admin/customers/:id", async (req, res) => { if (!await requireAdmin(req, res)) return; const customer = await db.getCustomerWithRewards(Number(req.params.id)); if (!customer) { res.status(404).json({ error: "العميل غير موجود." }); return; } res.json({ customer }); });
  app.post("/api/admin/customers/:id/rewards", async (req, res) => { const admin = await requireAdmin(req, res); if (!admin) return; try { const customer = await db.getCustomerWithRewards(Number(req.params.id)); if (!customer) { res.status(404).json({ error: "العميل غير موجود." }); return; } const reward = await db.createCustomerReward(customer.id, sanitizeReward(req.body ?? {}), admin.id); res.status(201).json({ reward }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "تعذر إرسال الحافز." }); } });
  app.patch("/api/admin/rewards/:id", async (req, res) => { if (!await requireAdmin(req, res)) return; await db.setCustomerRewardActive(Number(req.params.id), req.body?.isActive === true); res.json({ ok: true }); });
}
