import { and, desc, eq, ne } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { customerRewards, marketingNotificationRecipients, marketingNotifications, pricingSettings, referralSettings, referrals, supportConversations, supportMessages, type InsertUser, userPreferences, orderItems, orderMessages, orderNotifications, orders, productCategoryAssignments, productColors, productImages, productReviews, products, productSizes, productTrendTags, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;

export async function getDb() {
  if (!_db && process.env.DATABASE_URL) _db = drizzle(process.env.DATABASE_URL);
  return _db;
}

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb();
  if (!db) throw new Error("Database not available");
  const values: InsertUser = { openId: user.openId };
  const updateSet: Record<string, unknown> = {};
  const fields = ["name", "email", "loginMethod", "lastSignedIn", "phone", "passwordHash", "firstName", "secondName", "thirdName", "familyName", "governorate"] as const;
  for (const field of fields) if (user[field] !== undefined) { (values as Record<string, unknown>)[field] = user[field]; updateSet[field] = user[field]; }
  if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; }
  else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; }
  if (!values.lastSignedIn) { values.lastSignedIn = new Date(); updateSet.lastSignedIn = values.lastSignedIn; }
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}

export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.openId, openId)).limit(1))[0]; }
export async function getUserByPhone(phone: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.phone, phone)).limit(1))[0]; }

export type PhoneRegistrationRecord = { openId: string; name: string; firstName: string; secondName: string; thirdName: string; familyName: string; governorate: string; phone: string; passwordHash: string; };
export async function createPhoneUser(record: PhoneRegistrationRecord) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(users).values({ ...record, loginMethod: "phone", role: "user" }); return getUserByPhone(record.phone); }
export function referralCodeForUser(userId: number) { return `TDS-${userId.toString(36).toUpperCase()}-${(userId * 7919).toString(36).toUpperCase()}`; }
export async function recordReferral(invitedUserId: number, code?: string) { const db = await getDb(); if (!db || !code) return; const inviter = (await db.select().from(users).where(eq(users.id, Number.parseInt(code.split("-")[1] ?? "", 36))).limit(1))[0]; if (!inviter || inviter.id === invitedUserId || inviter.role !== "user") return; await db.insert(referrals).values({ inviterUserId: inviter.id, invitedUserId, referralCode: code }).onDuplicateKeyUpdate({ set: { referralCode: code } }); }
export async function getReferralSummary(userId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const settings = (await db.select().from(referralSettings).limit(1))[0]; const entries = await db.select().from(referrals).where(eq(referrals.inviterUserId, userId)); return { isEnabled: settings?.isEnabled ?? false, code: referralCodeForUser(userId), invitedCount: entries.length }; }
export async function listReferralLeaders() { const db = await getDb(); if (!db) return []; const all = await db.select().from(referrals).orderBy(desc(referrals.createdAt)); const groups = new Map<number, typeof all>(); all.forEach((row) => groups.set(row.inviterUserId, [...(groups.get(row.inviterUserId) ?? []), row])); return Promise.all([...groups.entries()].map(async ([userId, entries]) => { const user = (await db.select().from(users).where(eq(users.id, userId)).limit(1))[0]; return { userId, name: user ? customerName(user) : "عميل", phone: user?.phone ?? "—", governorate: user?.governorate ?? "غير محددة", invitedCount: entries.length, referralCode: referralCodeForUser(userId) }; })).then((rows) => rows.sort((a, b) => b.invitedCount - a.invitedCount)); }
export async function setReferralEnabled(isEnabled: boolean, adminId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const row = (await db.select().from(referralSettings).limit(1))[0]; if (row) await db.update(referralSettings).set({ isEnabled, updatedByUserId: adminId }).where(eq(referralSettings.id, row.id)); else await db.insert(referralSettings).values({ isEnabled, updatedByUserId: adminId }); return { isEnabled }; }
export type CurrencyCode = "YER" | "SAR" | "USD";
export async function getCurrencyPreference(userId: number) { const db = await getDb(); if (!db) return "YER" as CurrencyCode; return ((await db.select().from(userPreferences).where(eq(userPreferences.userId, userId)).limit(1))[0]?.currency ?? "YER") as CurrencyCode; }
export async function setCurrencyPreference(userId: number, currency: CurrencyCode) { const db = await getDb(); if (!db) throw new Error("Database not available"); const row = (await db.select().from(userPreferences).where(eq(userPreferences.userId, userId)).limit(1))[0]; if (row) await db.update(userPreferences).set({ currency }).where(eq(userPreferences.id, row.id)); else await db.insert(userPreferences).values({ userId, currency }); return { currency }; }
export async function getPricingSettings() { const db = await getDb(); if (!db) return { outsideIbbMarkupPercent: 0, freeShippingOutsideIbb: true }; const row = (await db.select().from(pricingSettings).limit(1))[0]; return row ? { outsideIbbMarkupPercent: row.outsideIbbMarkupPercent, freeShippingOutsideIbb: row.freeShippingOutsideIbb } : { outsideIbbMarkupPercent: 0, freeShippingOutsideIbb: true }; }
export async function updatePricingSettings(input: { outsideIbbMarkupPercent: number; freeShippingOutsideIbb: boolean }, adminId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = (await db.select().from(pricingSettings).limit(1))[0]; if (existing) await db.update(pricingSettings).set({ ...input, updatedByUserId: adminId }).where(eq(pricingSettings.id, existing.id)); else await db.insert(pricingSettings).values({ ...input, updatedByUserId: adminId }); return getPricingSettings(); }
async function hydrateSupport(row: typeof supportConversations.$inferSelect) { const db = await getDb(); if (!db) throw new Error("Database not available"); const messages = await db.select().from(supportMessages).where(eq(supportMessages.conversationId, row.id)).orderBy(supportMessages.createdAt); return { id: row.id, userId: row.userId, status: row.status, messages: messages.map((message) => ({ id: message.id, senderRole: message.senderRole, body: message.body, createdAt: message.createdAt.toISOString() })) }; }
export async function getSupportConversation(userId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); let row = (await db.select().from(supportConversations).where(eq(supportConversations.userId, userId)).limit(1))[0]; if (!row) { const result = await db.insert(supportConversations).values({ userId }); row = (await db.select().from(supportConversations).where(eq(supportConversations.id, Number(result[0].insertId))).limit(1))[0]; } return hydrateSupport(row); }
export async function addSupportMessage(conversationId: number, senderId: number, senderRole: "customer" | "admin", body: string) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (!body.trim()) throw new Error("اكتبي رسالة قبل الإرسال."); await db.insert(supportMessages).values({ conversationId, senderId, senderRole, body: body.trim() }); const row = (await db.select().from(supportConversations).where(eq(supportConversations.id, conversationId)).limit(1))[0]; return hydrateSupport(row); }
export async function listSupportConversations() { const db = await getDb(); if (!db) return []; const rows = await db.select().from(supportConversations).orderBy(desc(supportConversations.updatedAt)); return Promise.all(rows.map(hydrateSupport)); }

export type CustomerRewardInput = { rewardType: "gift" | "coupon" | "order_threshold" | "quantity_threshold"; title: string; couponCode?: string; discountType: "fixed" | "percent"; discountValue: number; minimumOrderAmount: number; minimumQuantity: number; giftName?: string; isActive: boolean; };
function rewardView(row: typeof customerRewards.$inferSelect) { return { id: row.id, rewardType: row.rewardType, title: row.title, couponCode: row.couponCode, discountType: row.discountType, discountValue: row.discountValue, minimumOrderAmount: row.minimumOrderAmount, minimumQuantity: row.minimumQuantity, giftName: row.giftName, isActive: row.isActive, expiresAt: row.expiresAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString() }; }
function customerName(row: typeof users.$inferSelect) { return [row.firstName, row.secondName, row.thirdName, row.familyName].filter(Boolean).join(" ") || row.name || "عميل بدون اسم"; }
export async function listCustomers(governorate?: string) { const db = await getDb(); if (!db) return []; const rows = await db.select().from(users).where(eq(users.role, "user")).orderBy(desc(users.createdAt)); const filtered = governorate && governorate !== "الكل" ? rows.filter((row) => row.governorate === governorate) : rows; return Promise.all(filtered.map(async (row) => ({ id: row.id, name: customerName(row), phone: row.phone ?? "—", governorate: row.governorate ?? "غير محددة", createdAt: row.createdAt.toISOString(), rewardCount: (await db.select().from(customerRewards).where(eq(customerRewards.userId, row.id))).length }))); }
export async function getCustomerWithRewards(userId: number) { const db = await getDb(); if (!db) return undefined; const row = (await db.select().from(users).where(eq(users.id, userId)).limit(1))[0]; if (!row || row.role !== "user") return undefined; const rewards = await db.select().from(customerRewards).where(eq(customerRewards.userId, userId)).orderBy(desc(customerRewards.createdAt)); return { id: row.id, name: customerName(row), phone: row.phone ?? "—", governorate: row.governorate ?? "غير محددة", createdAt: row.createdAt.toISOString(), rewards: rewards.map(rewardView) }; }
export async function createCustomerReward(userId: number, input: CustomerRewardInput, assignedByUserId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const result = await db.insert(customerRewards).values({ userId, rewardType: input.rewardType, title: input.title, couponCode: input.couponCode || null, discountType: input.discountType, discountValue: input.discountValue, minimumOrderAmount: input.minimumOrderAmount, minimumQuantity: input.minimumQuantity, giftName: input.giftName || null, isActive: input.isActive, assignedByUserId }); const row = (await db.select().from(customerRewards).where(eq(customerRewards.id, Number(result[0].insertId))).limit(1))[0]; return row ? rewardView(row) : undefined; }
export async function setCustomerRewardActive(rewardId: number, isActive: boolean) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.update(customerRewards).set({ isActive }).where(eq(customerRewards.id, rewardId)); }
export async function listActiveCustomerRewards(userId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select().from(customerRewards).where(and(eq(customerRewards.userId, userId), eq(customerRewards.isActive, true))).orderBy(desc(customerRewards.createdAt)); return rows.filter((row) => !row.expiresAt || row.expiresAt > new Date()).map(rewardView); }
export async function validateCustomerCoupon(userId: number, code: string, orderAmount: number, quantity: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const reward = (await db.select().from(customerRewards).where(and(eq(customerRewards.userId, userId), eq(customerRewards.couponCode, code), eq(customerRewards.isActive, true))).limit(1))[0]; if (!reward || (reward.expiresAt && reward.expiresAt <= new Date())) throw new Error("هذا الكوبون غير متاح لحسابك."); if (reward.minimumOrderAmount > orderAmount) throw new Error(`هذا الكوبون يتطلب شراء بقيمة ${reward.minimumOrderAmount} ر.ي على الأقل.`); if (reward.minimumQuantity > quantity) throw new Error(`هذا الكوبون يتطلب ${reward.minimumQuantity} قطع على الأقل.`); const discount = reward.discountType === "percent" ? Math.round(orderAmount * reward.discountValue / 100) : reward.discountValue; return { id: reward.id, title: reward.title, couponCode: reward.couponCode, discount: Math.min(orderAmount, discount) }; }

export type OrderLineInput = { productId: number; color: string; size: string; quantity: number };
export type OrderStatus = "pending_payment" | "payment_proof_sent" | "paid_shipping" | "cancelled";
type OrderMessageInput = { body?: string; imageStorageKey?: string; imageUrl?: string };
function orderStatusLabel(status: OrderStatus) { return ({ pending_payment: "بانتظار إشعار الدفع", payment_proof_sent: "تم إرسال إشعار الدفع", paid_shipping: "تم الدفع وجارٍ الشحن", cancelled: "تم إلغاء الطلب" } as const)[status]; }
async function hydrateOrder(row: typeof orders.$inferSelect) { const db = await getDb(); if (!db) throw new Error("Database not available"); const [items, messages, customer] = await Promise.all([db.select().from(orderItems).where(eq(orderItems.orderId, row.id)), db.select().from(orderMessages).where(eq(orderMessages.orderId, row.id)).orderBy(orderMessages.createdAt), db.select().from(users).where(eq(users.id, row.userId)).limit(1)]); return { id: row.id, orderCode: row.orderCode, userId: row.userId, status: row.status as OrderStatus, statusLabel: orderStatusLabel(row.status as OrderStatus), totalAmount: row.totalAmount, createdAt: row.createdAt.toISOString(), customer: customer[0] ? { name: customerName(customer[0]), phone: customer[0].phone ?? "—", governorate: customer[0].governorate ?? "غير محددة" } : undefined, items: items.map((item) => ({ id: item.id, productId: item.productId, productName: item.productName, imageUrl: item.imageUrl, color: item.color, size: item.size, unitPrice: item.unitPrice, quantity: item.quantity })), messages: messages.map((message) => ({ id: message.id, senderRole: message.senderRole, body: message.body, imageUrl: message.imageUrl, createdAt: message.createdAt.toISOString() })) }; }
export async function createOrderForCustomer(userId: number, input: OrderLineInput[]) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (!input.length) throw new Error("اختاري صنفًا واحدًا على الأقل لإنشاء الطلب."); const verified = await Promise.all(input.map(async (line) => { if (!Number.isInteger(line.productId) || !Number.isInteger(line.quantity) || line.quantity < 1 || line.quantity > 99) throw new Error("توجد كمية غير صحيحة في الطلب."); const product = await getProduct(line.productId); if (!product) throw new Error("أحد الأصناف المختارة لم يعد متاحًا."); return { product, color: line.color.trim() || "افتراضي", size: line.size.trim() || "مقاس موحد", quantity: line.quantity }; })); const totalAmount = verified.reduce((total, line) => total + line.product.price * line.quantity, 0); const orderCode = `TDS-${Date.now().toString().slice(-8)}-${Math.floor(Math.random() * 900 + 100)}`; const result = await db.insert(orders).values({ orderCode, userId, totalAmount }); const orderId = Number(result[0].insertId); await db.insert(orderItems).values(verified.map((line) => ({ orderId, productId: Number(line.product.id), productName: line.product.name, imageUrl: line.product.images[0]?.url ?? null, color: line.color, size: line.size, unitPrice: line.product.price, quantity: line.quantity }))); await db.insert(orderMessages).values({ orderId, senderId: userId, senderRole: "system", body: "تم إنشاء طلبك. أرسلي إشعار الدفع هنا ليتم مراجعته من الإدارة." }); return hydrateOrder((await db.select().from(orders).where(eq(orders.id, orderId)).limit(1))[0]); }
export async function getOrderOwner(orderId: number) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(orders).where(eq(orders.id, orderId)).limit(1))[0]; }
export async function getOrderDetails(orderId: number) { const row = await getOrderOwner(orderId); return row ? hydrateOrder(row) : undefined; }
export async function listOrdersForCustomer(userId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select().from(orders).where(eq(orders.userId, userId)).orderBy(desc(orders.createdAt)); return Promise.all(rows.map(hydrateOrder)); }
export async function listOrdersForAdmin() { const db = await getDb(); if (!db) return []; const rows = await db.select().from(orders).orderBy(desc(orders.updatedAt)); return Promise.all(rows.map(hydrateOrder)); }
export async function addOrderMessage(orderId: number, senderId: number, senderRole: "customer" | "admin", input: OrderMessageInput) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (!input.body?.trim() && !input.imageUrl) throw new Error("أرسلي نصًا أو صورة واحدة على الأقل."); await db.insert(orderMessages).values({ orderId, senderId, senderRole, body: input.body?.trim() || null, imageStorageKey: input.imageStorageKey || null, imageUrl: input.imageUrl || null }); if (senderRole === "customer" && input.imageUrl) await db.update(orders).set({ status: "payment_proof_sent" }).where(eq(orders.id, orderId)); return getOrderDetails(orderId); }
export async function markOrderPaidShipping(orderId: number, adminId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const order = await getOrderOwner(orderId); if (!order) throw new Error("الطلب غير موجود."); await db.update(orders).set({ status: "paid_shipping" }).where(eq(orders.id, orderId)); const message = "تم قبول طلبك وسيتم الشحن بأسرع وقت."; await db.insert(orderMessages).values({ orderId, senderId: adminId, senderRole: "system", body: message }); await db.insert(orderNotifications).values({ userId: order.userId, orderId, title: "تم قبول طلبك", body: message }); return getOrderDetails(orderId); }
export async function listCustomerNotifications(userId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select().from(orderNotifications).where(eq(orderNotifications.userId, userId)).orderBy(desc(orderNotifications.createdAt)); return rows.map((row) => ({ id: row.id, orderId: row.orderId, title: row.title, body: row.body, isRead: row.isRead, createdAt: row.createdAt.toISOString() })); }
export type MarketingNotificationInput = { title: string; body: string; audienceType: "governorate" | "single" | "selected"; governorate?: string; userIds: number[]; productId?: number; imageStorageKey?: string; imageUrl?: string };
export async function createMarketingNotification(input: MarketingNotificationInput, adminId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const allCustomers = await db.select().from(users).where(eq(users.role, "user")); const targetIds = input.audienceType === "governorate" ? allCustomers.filter((user) => user.governorate === input.governorate).map((user) => user.id) : input.audienceType === "single" ? input.userIds.slice(0, 1) : [...new Set(input.userIds)]; if (!targetIds.length) throw new Error("لم يتم العثور على عملاء مطابقين للإشعار."); const result = await db.insert(marketingNotifications).values({ title: input.title, body: input.body, audienceType: input.audienceType, governorate: input.governorate || null, productId: input.productId || null, imageStorageKey: input.imageStorageKey || null, imageUrl: input.imageUrl || null, createdByUserId: adminId }); const notificationId = Number(result[0].insertId); await db.insert(marketingNotificationRecipients).values(targetIds.map((userId) => ({ notificationId, userId }))); return { id: notificationId, recipientCount: targetIds.length }; }
export async function listMarketingNotificationsForUser(userId: number) { const db = await getDb(); if (!db) return []; const recipients = await db.select().from(marketingNotificationRecipients).where(eq(marketingNotificationRecipients.userId, userId)).orderBy(desc(marketingNotificationRecipients.createdAt)); return Promise.all(recipients.map(async (recipient) => { const row = (await db.select().from(marketingNotifications).where(eq(marketingNotifications.id, recipient.notificationId)).limit(1))[0]; return row ? { id: row.id, title: row.title, body: row.body, imageUrl: row.imageUrl, productId: row.productId, isRead: recipient.isRead, createdAt: row.createdAt.toISOString() } : undefined; })).then((rows) => rows.filter(Boolean)); }

export type ProductOptionInput = { name: string; hex: string };
export type ProductSizeInput = { label: string; stock: number };
export type ProductImageInput = { storageKey: string; url: string; sortOrder: number };
export type ProductInput = { productCode?: string; name: string; category: string; categories: string[]; description: string; details?: string; material?: string; price: number; discountPercent: number; shippingNote?: string; isTrending: boolean; trendTags: string[]; isPublished: boolean; colors: ProductOptionInput[]; sizes: ProductSizeInput[]; images: ProductImageInput[]; };

export type StoreProduct = { id: string; productCode: string; name: string; category: string; categories: string[]; description: string; details: string; material: string; price: number; originalPrice: number; discountPercent: number; shippingNote: string; isTrending: boolean; trendTags: string[]; images: { id: number; url: string; sortOrder: number }[]; colors: { id: number; name: string; hex: string }[]; sizes: { id: number; label: string; stock: number }[]; rating: number; reviews: number; reviewsList: { id: number; rating: number; body: string; selectedColor: string | null; selectedSize: string | null; helpfulCount: number; author: string; createdAt: string }[]; };

function discountedPrice(price: number, discountPercent: number) { return Math.max(0, Math.round(price * (1 - discountPercent / 100))); }

async function hydrateProduct(row: typeof products.$inferSelect): Promise<StoreProduct> {
  const db = await getDb();
  if (!db) throw new Error("Database not available");
  const [images, colors, sizes, reviews, categoryRows, trendTagRows] = await Promise.all([
    db.select().from(productImages).where(eq(productImages.productId, row.id)).orderBy(productImages.sortOrder),
    db.select().from(productColors).where(eq(productColors.productId, row.id)),
    db.select().from(productSizes).where(eq(productSizes.productId, row.id)),
    db.select().from(productReviews).where(eq(productReviews.productId, row.id)).orderBy(desc(productReviews.createdAt)),
    db.select().from(productCategoryAssignments).where(eq(productCategoryAssignments.productId, row.id)),
    db.select().from(productTrendTags).where(eq(productTrendTags.productId, row.id)),
  ]);
  const rating = reviews.length ? reviews.reduce((total, review) => total + review.rating, 0) / reviews.length : 0;
  const categories = categoryRows.length ? categoryRows.map((entry) => entry.category) : [row.category];
  return { id: String(row.id), productCode: row.productCode, name: row.name, category: row.category, categories, description: row.description, details: row.details ?? "", material: row.material ?? "", price: discountedPrice(row.price, row.discountPercent), originalPrice: row.price, discountPercent: row.discountPercent, shippingNote: row.shippingNote ?? "", isTrending: row.isTrending, trendTags: trendTagRows.map((entry) => entry.tag), images: images.map((image) => ({ id: image.id, storageKey: image.storageKey, url: image.url, sortOrder: image.sortOrder })), colors: colors.map((color) => ({ id: color.id, name: color.name, hex: color.hex })), sizes: sizes.map((size) => ({ id: size.id, label: size.label, stock: size.stock })), rating: Number(rating.toFixed(2)), reviews: reviews.length, reviewsList: reviews.map((review) => ({ id: review.id, rating: review.rating, body: review.body, selectedColor: review.selectedColor, selectedSize: review.selectedSize, helpfulCount: review.helpfulCount, author: "عميل التخفيض الصح", createdAt: review.createdAt.toISOString() })) };
}

export async function listProducts(includeUnpublished = false) {
  const db = await getDb(); if (!db) return [];
  const rows = includeUnpublished ? await db.select().from(products).orderBy(desc(products.createdAt)) : await db.select().from(products).where(eq(products.isPublished, true)).orderBy(desc(products.createdAt));
  return Promise.all(rows.map(hydrateProduct));
}

export async function getProduct(productId: number) { const db = await getDb(); if (!db) return undefined; const row = (await db.select().from(products).where(eq(products.id, productId)).limit(1))[0]; return row ? hydrateProduct(row) : undefined; }
export async function searchProducts(query: string) { const normalized = query.trim().toLocaleLowerCase("ar"); if (!normalized) return listProducts(false); const matches = (await listProducts(false)).filter((product) => [product.productCode, product.name, product.description, product.details, product.category, ...product.categories, ...product.trendTags].join(" ").toLocaleLowerCase("ar").includes(normalized)); return matches; }
export async function findSimilarProducts(productId: number, category: string) { const db = await getDb(); if (!db) return []; const rows = await db.select().from(products).where(and(eq(products.isPublished, true), eq(products.category, category), ne(products.id, productId))).orderBy(desc(products.createdAt)).limit(6); return Promise.all(rows.map(hydrateProduct)); }

async function replaceOptions(productId: number, input: ProductInput) {
  const db = await getDb(); if (!db) throw new Error("Database not available");
  await Promise.all([db.delete(productImages).where(eq(productImages.productId, productId)), db.delete(productColors).where(eq(productColors.productId, productId)), db.delete(productSizes).where(eq(productSizes.productId, productId)), db.delete(productCategoryAssignments).where(eq(productCategoryAssignments.productId, productId)), db.delete(productTrendTags).where(eq(productTrendTags.productId, productId))]);
  if (input.images.length) await db.insert(productImages).values(input.images.map((image, index) => ({ productId, storageKey: image.storageKey, url: image.url, sortOrder: image.sortOrder ?? index })));
  if (input.colors.length) await db.insert(productColors).values(input.colors.map((color) => ({ productId, name: color.name, hex: color.hex })));
  if (input.sizes.length) await db.insert(productSizes).values(input.sizes.map((size) => ({ productId, label: size.label, stock: size.stock })));
  await db.insert(productCategoryAssignments).values(input.categories.map((category) => ({ productId, category })));
  if (input.isTrending && input.trendTags.length) await db.insert(productTrendTags).values(input.trendTags.map((tag) => ({ productId, tag })));
}

export async function createProduct(input: ProductInput, userId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const productCode = input.productCode || `TDS-${Date.now().toString().slice(-8)}`; const result = await db.insert(products).values({ productCode, name: input.name, category: input.category, description: input.description, details: input.details || null, material: input.material || null, price: input.price, discountPercent: input.discountPercent, shippingNote: input.shippingNote || null, isTrending: input.isTrending, isPublished: input.isPublished, createdByUserId: userId }); const id = Number(result[0].insertId); await replaceOptions(id, input); return getProduct(id); }
export async function updateProduct(productId: number, input: ProductInput) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.update(products).set({ productCode: input.productCode, name: input.name, category: input.category, description: input.description, details: input.details || null, material: input.material || null, price: input.price, discountPercent: input.discountPercent, shippingNote: input.shippingNote || null, isTrending: input.isTrending, isPublished: input.isPublished }).where(eq(products.id, productId)); await replaceOptions(productId, input); return getProduct(productId); }
