import { apiCall } from "@/lib/_core/api";

export type StoreProduct = { id: string; productCode: string; name: string; category: string; categories: string[]; description: string; details: string; material: string; price: number; originalPrice: number; discountPercent: number; shippingNote: string; isTrending: boolean; trendTags: string[]; images: { id: number; storageKey: string; url: string; sortOrder: number }[]; colors: { id: number; name: string; hex: string }[]; sizes: { id: number; label: string; stock: number }[]; rating: number; reviews: number; reviewsList: { id: number; rating: number; body: string; selectedColor: string | null; selectedSize: string | null; helpfulCount: number; author: string; createdAt: string }[]; };
export type ProductEditorPayload = { productCode?: string; name: string; category: string; categories: string[]; description: string; details: string; material: string; price: number; discountPercent: number; shippingNote: string; isTrending: boolean; trendTags: string[]; isPublished: boolean; colors: { name: string; hex: string }[]; sizes: { label: string; stock: number }[]; images?: { dataUrl: string; fileName: string; sortOrder: number }[]; existingImages?: { storageKey: string; url: string; sortOrder: number }[]; newImages?: { dataUrl: string; fileName: string; sortOrder: number }[]; };

export async function getProducts(query = "") { return (await apiCall<{ products: StoreProduct[] }>(`/api/products${query ? `?q=${encodeURIComponent(query)}` : ""}`)).products; }
export async function getProduct(id: string) { return apiCall<{ product: StoreProduct; similar: StoreProduct[] }>(`/api/products/${id}`); }
export async function getAdminProducts() { return (await apiCall<{ products: StoreProduct[] }>("/api/admin/products")).products; }
export async function createProduct(payload: ProductEditorPayload) { return apiCall<{ product: StoreProduct }>("/api/admin/products", { method: "POST", body: JSON.stringify(payload) }); }
export async function updateProduct(id: string, payload: ProductEditorPayload) { return apiCall<{ product: StoreProduct }>(`/api/admin/products/${id}`, { method: "PATCH", body: JSON.stringify(payload) }); }
