import { apiCall } from "@/lib/_core/api";

export type StorefrontTheme = { id:number; name:string; tokens:Record<string,any>; layout:Record<string,any>; sections:Record<string,any>[]; is_global:boolean };
export type StorefrontAction = { label: string; url: string; visible: boolean };
export type StorefrontCard = { id: string; title: string; subtitle: string; imageUrl: string; url: string; badge: string; visible: boolean; sortOrder: number; isActive: boolean };
export type StorefrontSlide = StorefrontCard & { ctaLabel: string };
export type StorefrontCircle = { id: string; title: string; targetCategory: string; imageUrl: string; url: string; visible: boolean; sortOrder: number; isActive: boolean };
export type StorefrontPromo = { enabled?: boolean; flashTitle: string; flashSubtitle: string; flashMode: string; freeShippingTitle: string; freeShippingSubtitle: string; freeShippingCategory: string };
export type StorefrontTab = { id: string; type: string; title: string; searchPlaceholder: string; isActive: boolean; sortOrder: number; slides: StorefrontSlide[]; circles: StorefrontCircle[]; cards: StorefrontCard[]; actions: StorefrontAction[]; promo?: StorefrontPromo; config: ConfigRecord };
type ImagePayload = { dataUrl: string; fileName: string };
type ConfigRecord = Record<string, any>;
type RawSection = { id: number | string; title?: string; section_type?: string; type?: string; vendor?: number | null; config?: ConfigRecord; sort_order?: number; is_visible?: boolean };
type SectionsResponse = RawSection[] | { results?: RawSection[]; data?: RawSection[] };
function asRecord(value: unknown): ConfigRecord { return value && typeof value === "object" && !Array.isArray(value) ? value as ConfigRecord : {}; }
function asArray(value: unknown): ConfigRecord[] { return Array.isArray(value) ? value.filter((item): item is ConfigRecord => Boolean(item) && typeof item === "object") : []; }
function text(value: unknown, fallback = "") { return typeof value === "string" ? value : value == null ? fallback : String(value); }
function bool(value: unknown, fallback = true) { return typeof value === "boolean" ? value : fallback; }
function number(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function toCard(sectionId: string, item: ConfigRecord, index: number): StorefrontCard { const active = bool(item.visible ?? item.isActive ?? item.is_active); return { id: text(item.id, `${sectionId}::card::${index}`), title: text(item.title), subtitle: text(item.subtitle), imageUrl: text(item.imageUrl ?? item.image_url ?? item.url), url: text(item.url ?? item.link), badge: text(item.badge), visible: active, sortOrder: number(item.sortOrder ?? item.sort_order, index), isActive: active }; }
function toSlide(sectionId: string, item: ConfigRecord, index: number): StorefrontSlide { const card = toCard(sectionId, item, index); return { ...card, ctaLabel: text(item.ctaLabel ?? item.cta_label, "تسوّق الآن") }; }
function toCircle(sectionId: string, item: ConfigRecord, index: number): StorefrontCircle { const active = bool(item.visible ?? item.isActive ?? item.is_active); return { id: text(item.id, `${sectionId}::circle::${index}`), title: text(item.title), targetCategory: text(item.targetCategory ?? item.target_category), imageUrl: text(item.imageUrl ?? item.image_url ?? item.url), url: text(item.url ?? item.link), visible: active, sortOrder: number(item.sortOrder ?? item.sort_order, index), isActive: active }; }
function toAction(item: ConfigRecord): StorefrontAction { return { label: text(item.label ?? item.title), url: text(item.url ?? item.link), visible: bool(item.visible, true) }; }
function toTab(section: RawSection, theme?:StorefrontTheme|null): StorefrontTab { const id = text(section.id); const config: ConfigRecord = {...asRecord(section.config), ...(theme ? {__theme:theme} : {})}; const type = text(section.section_type ?? section.type, "product_grid"); const slides = asArray(config.slides).map((item, index) => toSlide(id, item, index)); if (!slides.length && ["hero", "banner"].includes(type.toLowerCase()) && (config.imageUrl || config.image_url || config.url)) slides.push(toSlide(id, config, 0)); const circles = asArray(config.circles ?? config.categories ?? config.collections).map((item, index) => toCircle(id, item, index)); const cards = asArray(config.cards ?? config.banners ?? config.items).map((item, index) => toCard(id, item, index)); const actions = asArray(config.actions ?? config.buttons).map(toAction); const promoConfig = asRecord(config.promo); const promo: StorefrontPromo = { enabled: bool(promoConfig.enabled, false), flashTitle: text(promoConfig.flashTitle, "تخفيضات سريعة"), flashSubtitle: text(promoConfig.flashSubtitle, "عرض المزيد"), flashMode: text(promoConfig.flashMode, "flash"), freeShippingTitle: text(promoConfig.freeShippingTitle, "شحن مجاني"), freeShippingSubtitle: text(promoConfig.freeShippingSubtitle, "أضف المزيد للحصول عليه"), freeShippingCategory: text(promoConfig.freeShippingCategory) }; return { id, type, title: text(section.title, "الرئيسية"), searchPlaceholder: text(config.searchPlaceholder ?? config.search_placeholder, "ابحث عن منتج أو متجر"), isActive: bool(section.is_visible), sortOrder: number(section.sort_order), slides: slides.filter(item => item.visible).sort((a,b)=>a.sortOrder-b.sortOrder), circles: circles.filter(item => item.visible).sort((a,b)=>a.sortOrder-b.sortOrder), cards: cards.filter(item => item.visible).sort((a,b)=>a.sortOrder-b.sortOrder), actions: actions.filter(item => item.visible), promo, config }; }
function extractSections(response: SectionsResponse): RawSection[] { return Array.isArray(response) ? response : response.results ?? response.data ?? []; }
async function fetchSections(endpoint: string) { const response = await apiCall<SectionsResponse>(endpoint); return extractSections(response); }
async function fetchTabs(endpoint: string, theme?:StorefrontTheme|null) { const sections = await fetchSections(endpoint); return sections.sort((a,b)=>number(a.sort_order)-number(b.sort_order)).map(section=>toTab(section,theme)); }
async function fetchSection(id: string) { return apiCall<RawSection>(`/api/storefront-sections/${encodeURIComponent(id)}/`); }
async function saveSection(id: string, changes: { title?: string; sort_order?: number; is_visible?: boolean; config?: ConfigRecord }) { await apiCall(`/api/storefront-sections/${encodeURIComponent(id)}/`, { method: "PATCH", body: JSON.stringify(changes) }); return { tabs: await getAdminStorefront() }; }
function configWithItems(section: RawSection, key: string, items: ConfigRecord[]) { return { ...asRecord(section.config), [key]: items }; }
function splitVisualId(id: string) { const match = id.match(/^(.+?)::(slide|circle|card)::(.+)$/); return match ? { sectionId: match[1], kind: match[2] as "slide"|"circle"|"card", itemId: match[3] } : undefined; }
async function updateVisual(id: string, kind: "slide"|"circle"|"card", changes: ConfigRecord) { const parsed=splitVisualId(id); if(!parsed||parsed.kind!==kind) throw new Error("معرّف العنصر غير صالح"); const section=await fetchSection(parsed.sectionId); const config=asRecord(section.config); const key=kind === "slide" ? "slides" : kind === "circle" ? "circles" : "cards"; const items=asArray(config[key]); const index=items.findIndex((item,itemIndex)=>text(item.id,`${parsed.sectionId}::${kind}::${itemIndex}`)===id || text(item.id)===parsed.itemId); if(index<0) throw new Error("العنصر غير موجود"); const normalized={...changes}; if("isActive" in normalized){ normalized.visible=Boolean(normalized.isActive); delete normalized.isActive; } items[index]={...items[index],...normalized}; return saveSection(parsed.sectionId,{config:configWithItems(section,key,items)}); }
async function deleteVisual(id: string, kind: "slide"|"circle"|"card") { const parsed=splitVisualId(id); if(!parsed||parsed.kind!==kind) throw new Error("معرّف العنصر غير صالح"); const section=await fetchSection(parsed.sectionId); const config=asRecord(section.config); const key=kind === "slide" ? "slides" : kind === "circle" ? "circles" : "cards"; const items=asArray(config[key]).filter((item,index)=>text(item.id,`${parsed.sectionId}::${kind}::${index}`)!==id && text(item.id)!==parsed.itemId); return saveSection(parsed.sectionId,{config:configWithItems(section,key,items)}); }
export async function getStorefront(){ const response=await apiCall<{data?:RawSection[];theme?:StorefrontTheme|null}>("/api/home/"); return (response.data??[]).map(section=>toTab(section,response.theme)).filter(tab=>tab.isActive); }
export async function getVendorStorefront(slug:string){ const response=await apiCall<{data?:RawSection[];theme?:StorefrontTheme|null}>(`/api/stores/${encodeURIComponent(slug)}/home/`); return (response.data??[]).map(section=>toTab(section,response.theme)).filter(tab=>tab.isActive); }
export async function getAdminStorefront(){ return fetchTabs("/api/storefront-sections/"); }
export async function createTab(payload:{title:string;searchPlaceholder:string;sectionType?:string}){ await apiCall("/api/storefront-sections/",{method:"POST",body:JSON.stringify({title:payload.title,section_type:payload.sectionType??"banner",config:{searchPlaceholder:payload.searchPlaceholder,slides:[],circles:[],cards:[],actions:[],promo:{enabled:false}},sort_order:Date.now(),is_visible:true})}); return {tabs:await getAdminStorefront()}; }
export async function updateTab(id:string,payload:Partial<{title:string;searchPlaceholder:string;isActive:boolean;sortOrder:number;sectionType:string;config:ConfigRecord}>){ const section=await fetchSection(id); const config={...asRecord(section.config),...(payload.config??{})}; if(payload.searchPlaceholder!==undefined) config.searchPlaceholder=payload.searchPlaceholder; return saveSection(id,{title:payload.title,sort_order:payload.sortOrder,is_visible:payload.isActive,config}); }
export async function deleteTab(id:string){ await apiCall(`/api/storefront-sections/${encodeURIComponent(id)}/`,{method:"DELETE"}); return {tabs:await getAdminStorefront()}; }
export async function updatePromos(id:string,promo:StorefrontPromo){const section=await fetchSection(id);return saveSection(id,{config:{...asRecord(section.config),promo:{...promo,enabled:promo.enabled??true}}});}
export async function createSlide(tabId:string,payload:{title:string;subtitle:string;ctaLabel:string;url?:string;image:ImagePayload}){const section=await fetchSection(tabId);const config=asRecord(section.config);const slides=asArray(config.slides);slides.push({id:`${tabId}::slide::${Date.now()}`,title:payload.title,subtitle:payload.subtitle,ctaLabel:payload.ctaLabel,url:payload.url??"",imageUrl:payload.image.dataUrl,fileName:payload.image.fileName,visible:true,sortOrder:slides.length});return saveSection(tabId,{config:configWithItems(section,"slides",slides)});}
export async function updateSlide(id:string,payload:Partial<{visible:boolean;isActive:boolean;sortOrder:number;url:string;title:string;subtitle:string;ctaLabel:string}>){return updateVisual(id,"slide",payload);}
export async function deleteSlide(id:string){return deleteVisual(id,"slide");}
export async function createCircle(tabId:string,payload:{title:string;targetCategory:string;url?:string;image?:ImagePayload}){const section=await fetchSection(tabId);const config=asRecord(section.config);const circles=asArray(config.circles);circles.push({id:`${tabId}::circle::${Date.now()}`,title:payload.title,targetCategory:payload.targetCategory,url:payload.url??"",imageUrl:payload.image?.dataUrl??"",fileName:payload.image?.fileName??"",visible:true,sortOrder:circles.length});return saveSection(tabId,{config:configWithItems(section,"circles",circles)});}
export async function updateCircle(id:string,payload:Partial<{visible:boolean;isActive:boolean;sortOrder:number;url:string;title:string;targetCategory:string}>){return updateVisual(id,"circle",payload);}
export async function deleteCircle(id:string){return deleteVisual(id,"circle");}
export async function createCard(tabId:string,payload:{title:string;subtitle:string;badge?:string;url?:string;image?:ImagePayload}){const section=await fetchSection(tabId);const config=asRecord(section.config);const cards=asArray(config.cards);cards.push({id:`${tabId}::card::${Date.now()}`,title:payload.title,subtitle:payload.subtitle,badge:payload.badge??"",url:payload.url??"",imageUrl:payload.image?.dataUrl??"",fileName:payload.image?.fileName??"",visible:true,sortOrder:cards.length});return saveSection(tabId,{config:configWithItems(section,"cards",cards)});}
export async function updateCard(id:string,payload:ConfigRecord){return updateVisual(id,"card",payload);}
export async function deleteCard(id:string){return deleteVisual(id,"card");}
