# Generated by Django 5.2.17 on 2026-09-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_catalogoption_delete_category_city_and_more'),
        ('communication', '0001_initial'),
        ('orders', '0002_delete_inventoryreservation_delete_order_and_more'),
        ('vendors', '0002_delete_vendorapplication_delete_vendorprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(name='Conversation'), migrations.DeleteModel(name='Message'), migrations.DeleteModel(name='Notification'), migrations.CreateModel(name='Conversation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('subject', models.CharField(blank=True, max_length=180)), ('is_closed', models.BooleanField(default=False)), ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_conversations', to=settings.AUTH_USER_MODEL)), ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='orders.order')), ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='vendors.vendorprofile'))], options={'db_table': 'marketplace_conversation'}), migrations.CreateModel(name='Message', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('body', models.TextField(blank=True)), ('attachment', models.ImageField(blank=True, null=True, upload_to='messages/')), ('is_read', models.BooleanField(default=False)), ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.conversation')), ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL))], options={'db_table': 'marketplace_message'}), migrations.CreateModel(name='Notification', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(max_length=180)), ('body', models.TextField()), ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')), ('is_read', models.BooleanField(default=False)), ('audience', models.JSONField(blank=True, default=dict)), ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='catalog.product')), ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL))], options={'db_table': 'marketplace_notification'})]
        ),
    ]
