import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useMemo, useState } from "react";

import { ProductCard } from "@/components/product-card";
import { useProducts } from "@/hooks/use-products";

type CategoryItem = { id: string; title: string };
export default function CategoriesScreen() {
  const { products, loading, refresh } = useProducts(); const [selected, setSelected] = useState("all");
  const categories = useMemo<CategoryItem[]>(() => [{ id: "all", title: "الكل" }, ...[...new Set(products.flatMap((product) => product.categories?.length ? product.categories : [product.category]))].map((title) => ({ id: title, title }))], [products]);
  const current = categories.find((category) => category.id === selected) ?? categories[0]; const visibleProducts = useMemo(() => selected === "all" ? products : products.filter((product) => (product.categories?.length ? product.categories : [product.category]).includes(selected)), [products, selected]);
  return <View style={styles.page}><View style={styles.header}><View style={styles.searchGhost}><MaterialIcons name="photo-camera" size={20} color="#555555" /><Text style={styles.searchText}>ابحثي في الفئات</Text><MaterialIcons name="search" size={20} color="#171717" /></View><Text style={styles.title}>الفئات</Text></View><View style={styles.content}><View style={styles.side}><FlatList data={categories} keyExtractor={(item) => item.id} renderItem={({ item }) => <TouchableOpacity style={[styles.sideItem, selected === item.id && styles.sideItemActive]} onPress={() => setSelected(item.id)}><Text style={[styles.sideText, selected === item.id && styles.sideTextActive]}>{item.title}</Text></TouchableOpacity>} ListEmptyComponent={<Text style={styles.noCategories}>تظهر الفئات عند ربطها بالأصناف.</Text>} /></View><FlatList data={visibleProducts} keyExtractor={(item) => item.id} numColumns={2} columnWrapperStyle={visibleProducts.length > 1 ? styles.productRow : undefined} contentContainerStyle={styles.products} refreshing={loading} onRefresh={refresh} renderItem={({ item }) => <ProductCard product={item} />} ListHeaderComponent={<View style={styles.categoryHero}><Text style={styles.categoryHeroText}>{current?.title ?? "الكل"}</Text><Text style={styles.categoryHeroSub}>{selected === "all" ? "تصفّحي جميع الأصناف المنشورة" : "تظهر الأصناف المرتبطة بهذه الفئة"}</Text></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="category" size={40} color="#9D9D9D" /><Text style={styles.emptyText}>{loading ? "جارِ تحميل الأصناف" : "لا توجد أصناف في هذه الفئة بعد"}</Text></View>} /></View></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FFFFFF" }, header: { paddingHorizontal: 14, paddingTop: 9, paddingBottom: 9, borderBottomWidth: 1, borderColor: "#EEEEEE", flexDirection: "row-reverse", alignItems: "center", gap: 9 }, title: { fontSize: 17, color: "#171717", fontWeight: "900" }, searchGhost: { flex: 1, backgroundColor: "#F4F4F4", height: 39, paddingHorizontal: 10, flexDirection: "row-reverse", alignItems: "center", gap: 7 }, searchText: { flex: 1, color: "#727272", textAlign: "right", fontSize: 11 }, content: { flex: 1, flexDirection: "row-reverse" }, side: { width: 88, backgroundColor: "#F6F6F6" }, sideItem: { minHeight: 58, justifyContent: "center", alignItems: "center", paddingHorizontal: 8, borderRightWidth: 3, borderRightColor: "transparent" }, sideItemActive: { backgroundColor: "#FFFFFF", borderRightColor: "#171717" }, sideText: { color: "#747474", textAlign: "center", fontSize: 12 }, sideTextActive: { color: "#171717", fontWeight: "900" }, noCategories: { color: "#838383", fontSize: 9, textAlign: "center", padding: 9 }, products: { padding: 10, paddingBottom: 24 }, productRow: { gap: 9 }, categoryHero: { height: 92, marginBottom: 14, backgroundColor: "#F0F0F0", justifyContent: "center", alignItems: "flex-end", padding: 14 }, categoryHeroText: { color: "#171717", fontWeight: "900", fontSize: 22 }, categoryHeroSub: { color: "#777777", fontSize: 10, marginTop: 2, textAlign: "right" }, empty: { alignItems: "center", paddingTop: 30, width: "100%" }, emptyText: { color: "#777777", fontSize: 11, marginTop: 7 },
});
