import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useEffect, useMemo, useState } from "react";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { ProductCard } from "@/components/product-card";
import { useProducts } from "@/hooks/use-products";

export default function TrendsScreen() {
  const { products, loading, refresh } = useProducts();
  const tags = useMemo(() => [...new Set(products.filter((product) => product.isTrending).flatMap((product) => product.trendTags))], [products]);
  const [selectedTag, setSelectedTag] = useState<string | null>(null);
  useEffect(() => { if (!selectedTag && tags[0]) setSelectedTag(tags[0]); if (selectedTag && !tags.includes(selectedTag)) setSelectedTag(tags[0] ?? null); }, [selectedTag, tags]);
  const insets = useSafeAreaInsets();
  const trendingProducts = useMemo(() => products.filter((product) => product.isTrending && (selectedTag ? product.trendTags.includes(selectedTag) : true)), [products, selectedTag]);
  return <View style={[styles.page, { paddingTop: Math.max(insets.top, 0) }]}><FlatList data={trendingProducts} keyExtractor={(item) => item.id} numColumns={2} columnWrapperStyle={trendingProducts.length > 1 ? styles.row : undefined} contentContainerStyle={styles.list} refreshing={loading} onRefresh={refresh} renderItem={({ item }) => <ProductCard product={item} />} ListHeaderComponent={<View><View style={styles.hero}><Text style={styles.kicker}>THE EDIT</Text><Text style={styles.heroTitle}>مختارات رائجة</Text><Text style={styles.heroText}>اكتشفي الأصناف التي فعّلها المتجر ضمن ترنداته الحالية.</Text></View><View style={styles.tagSection}><View style={styles.tagTitleRow}><TouchableOpacity style={styles.allTags}><MaterialIcons name="apps" size={19} color="#171717" /></TouchableOpacity><View><Text style={styles.tagTitle}>اختاري الهاشتاج</Text><Text style={styles.tagSub}>تصفية سريعة للترندات</Text></View></View><FlatList horizontal inverted data={tags} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tags} renderItem={({ item }) => <TouchableOpacity onPress={() => setSelectedTag(item)} style={[styles.tag, selectedTag === item && styles.tagActive]}><Text style={[styles.tagText, selectedTag === item && styles.tagTextActive]}>#{item}</Text></TouchableOpacity>} ListEmptyComponent={!loading ? <Text style={styles.noTags}>لا توجد هاشتاجات ترندات منشورة بعد.</Text> : null} /></View><View style={styles.heading}><Text style={styles.headingText}>{selectedTag ? `#${selectedTag}` : "كل الترندات"}</Text><Text style={styles.count}>{trendingProducts.length} صنف</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="local-fire-department" size={44} color="#A0A0A0" /><Text style={styles.emptyTitle}>{loading ? "جارِ تحميل الترندات" : "لا توجد أصناف مفعلة للترندات"}</Text><Text style={styles.emptyText}>فعّلي خيار «إظهار الصنف في ترندات» وأضيفي هاشتاجًا من إدارة الأصناف.</Text></View>} /></View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FFFFFF" }, list: { paddingHorizontal: 12, paddingBottom: 25 }, hero: { height: 150, backgroundColor: "#171717", padding: 18, alignItems: "flex-end", justifyContent: "center", marginHorizontal: -12 }, kicker: { color: "#E60023", fontWeight: "900", fontSize: 10 }, heroTitle: { color: "#FFFFFF", fontWeight: "900", fontSize: 27, marginTop: 4 }, heroText: { color: "#D8D8D8", fontSize: 10, marginTop: 5, textAlign: "right" }, tagSection: { paddingTop: 16, paddingBottom: 4 }, tagTitleRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 2, marginBottom: 10 }, tagTitle: { color: "#171717", fontSize: 14, fontWeight: "900", textAlign: "right" }, tagSub: { color: "#888888", fontSize: 9, marginTop: 2, textAlign: "right" }, allTags: { width: 36, height: 36, backgroundColor: "#F1F1F1", alignItems: "center", justifyContent: "center" }, tags: { gap: 8, paddingBottom: 8 }, tag: { backgroundColor: "#F1F1F1", borderRadius: 2, paddingHorizontal: 11, paddingVertical: 8 }, tagActive: { backgroundColor: "#171717" }, tagText: { color: "#505050", fontSize: 11, fontWeight: "800" }, tagTextActive: { color: "#FFFFFF" }, noTags: { color: "#888888", fontSize: 11 }, heading: { flexDirection: "row-reverse", alignItems: "baseline", justifyContent: "space-between", paddingTop: 9, paddingBottom: 10 }, headingText: { color: "#171717", fontSize: 18, fontWeight: "900" }, count: { color: "#888888", fontSize: 10 }, row: { gap: 10 }, empty: { alignItems: "center", paddingVertical: 39, paddingHorizontal: 23 }, emptyTitle: { color: "#303030", fontSize: 15, fontWeight: "900", marginTop: 9 }, emptyText: { color: "#858585", fontSize: 11, textAlign: "center", marginTop: 5, lineHeight: 18 },
});
