# Generated by Django 5.2.17 on 2026-09-03 18:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(name='VendorApplication'), migrations.DeleteModel(name='VendorProfile'), migrations.CreateModel(name='VendorApplication', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('store_name', models.CharField(max_length=180)), ('description', models.TextField(blank=True)), ('phone', models.CharField(max_length=32)), ('address', models.CharField(blank=True, max_length=255)), ('documents', models.JSONField(blank=True, default=dict)), ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)), ('review_note', models.TextField(blank=True)), ('reviewed_at', models.DateTimeField(blank=True, null=True)), ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_application', to=settings.AUTH_USER_MODEL)), ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_applications_reviewed', to=settings.AUTH_USER_MODEL))], options={'db_table': 'marketplace_vendorapplication', 'ordering': ['-created_at']}), migrations.CreateModel(name='VendorProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('store_name', models.CharField(max_length=180)), ('slug', models.SlugField(blank=True, max_length=200, unique=True)), ('description', models.TextField(blank=True)), ('logo', models.ImageField(blank=True, null=True, upload_to='vendor/logos/')), ('cover', models.ImageField(blank=True, null=True, upload_to='vendor/covers/')), ('phone', models.CharField(blank=True, max_length=32)), ('address', models.CharField(blank=True, max_length=255)), ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('suspended', 'موقوف')], default='pending', max_length=20)), ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])), ('settings', models.JSONField(blank=True, default=dict)), ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL))], options={'db_table': 'marketplace_vendorprofile', 'ordering': ['-created_at']})]
        ),
    ]
