from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [("marketplace", "0002_services_and_wallet_holds")]
    operations = [
        migrations.CreateModel(name="VendorCityShipping", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("fee", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)), ("is_active", models.BooleanField(default=True)), ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vendor_shipping_fees", to="marketplace.city")), ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="city_shipping_fees", to="marketplace.vendorprofile"))], options={"constraints":[models.UniqueConstraint(fields=("vendor","city"), name="uniq_vendor_city_shipping")]}),
        migrations.CreateModel(name="MarketplaceOffice", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=180)), ("address", models.CharField(blank=True, max_length=255)), ("phone", models.CharField(blank=True, max_length=40)), ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)), ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)), ("image", models.ImageField(blank=True, null=True, upload_to="offices/")), ("is_active", models.BooleanField(default=True)), ("city", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="marketplace_office", to="marketplace.city"))]),
        migrations.CreateModel(name="OrderItemDecision", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("status", models.CharField(choices=[("pending","معلق"),("accepted","مقبول"),("rejected","مرفوض")], default="pending", max_length=20)), ("reason", models.TextField(blank=True)), ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="marketplace.user")), ("order_item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="decision", to="marketplace.orderitem"))]),
    ]