# Generated by Django 6.1 on 2026-08-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_address_gifttransfer_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='receiver_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التأكيد'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20),
        ),
    ]
