# Generated by Django 6.1 on 2026-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_brand_product_material_product_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
