# Generated by Django 5.2.17 on 2026-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_merge_storefront_and_order_chat'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryreservation',
            name='marketplace_i_order_i_d2a9a8_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='marketplace_is_acti_b54e10_idx',
            old_name='marketplace_c_active_n_1f1f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='marketplace_coupon__e4f58e_idx',
            old_name='marketplace_c_coupon_u_3e7e20_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='marketplace_created_265ee8_idx',
            old_name='marketplace_c_created_2f5f61_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryreservation',
            new_name='marketplace_order_i_511a97_idx',
            old_name='marketplace_i_order_s_2c1774_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryreservation',
            new_name='marketplace_expires_8e06c7_idx',
            old_name='marketplace_i_expires_4ea06b_idx',
        ),
        migrations.RenameIndex(
            model_name='orderchat',
            new_name='marketplace_custome_4646f8_idx',
            old_name='marketplace_o_customer_19c8cc_idx',
        ),
        migrations.RenameIndex(
            model_name='orderchat',
            new_name='marketplace_vendor__b38893_idx',
            old_name='marketplace_o_vendor_08fb2f_idx',
        ),
        migrations.RenameIndex(
            model_name='orderchat',
            new_name='marketplace_order_i_65fe02_idx',
            old_name='marketplace_o_order_v_0b3ab4_idx',
        ),
        migrations.RenameIndex(
            model_name='orderchatmessage',
            new_name='marketplace_chat_id_2cd04e_idx',
            old_name='marketplace_o_chat_id_c7b8dd_idx',
        ),
        migrations.RenameIndex(
            model_name='orderchatmessage',
            new_name='marketplace_chat_id_650094_idx',
            old_name='marketplace_o_chat_is_82b49d_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='marketplace_vendor__ede704_idx',
            old_name='marketplace_p_vendor_s_4d4e9e_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='marketplace_product_59d90a_idx',
            old_name='marketplace_pv_product_s_8b8b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='marketplace_product_a4c812_idx',
            old_name='marketplace_pv_dims_55be61_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='marketplace_product_2c75f8_idx',
            old_name='marketplace_pv_product_a_2b9f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontmedia',
            new_name='marketplace_vendor__4576fa_idx',
            old_name='marketplace_st_vendor_6d31f7_idx',
        ),
        migrations.RenameIndex(
            model_name='vendororder',
            new_name='marketplace_vendor__ad2742_idx',
            old_name='marketplace_v_vendor_i_7f0d8a_idx',
        ),
        migrations.RenameIndex(
            model_name='vendororder',
            new_name='marketplace_order_i_55497d_idx',
            old_name='marketplace_v_order_s_0b3aef_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
