# Generated by Django 5.2.17 on 2026-08-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_merge_catalog_and_storefront'),
        ('marketplace', '0014_remove_inventoryreservation_marketplace_i_order_i_d2a9a8_idx_and_more'),
    ]

    operations = [
    ]
